import os

asset_folder = os.path.join(os.path.dirname(__file__), '../dm_control/dm_control/suite/dog_assets/extras')
extra_sites_folder = os.path.join(os.path.dirname(__file__), 'extra_sites')
plane_folder = os.path.join(os.path.dirname(__file__), 'acsa_planes', 'v01')


class MTU:
  """Represents a musculo-tendon unit

  Note: There may be multiple mesh files for a muscle (e.g. triceps brachii contains three mesh files). Also, some
  muscles are missing (like MUSCm.triceps_brachii_lateral_R); in these situations we're using the contralateral muscle
  since they are equivalent in size and volume
  """

  def __init__(self, name, sites, mesh_name=None, scale_factor=1.0):
    self.name = name
    self.sites = sites
    self.scale_factor = scale_factor
    if mesh_name is None:
      mesh_name = [name]
    else:
      if not isinstance(mesh_name, list):
        mesh_name = [mesh_name]
    self.muscle_mesh_file = [os.path.join(asset_folder, f"MUSC{m}.stl") for m in mesh_name]
    self.plane_mesh_file = [os.path.join(plane_folder, f"PLANE{m}.stl") for m in mesh_name]


class Site:
  """Represents an individual site for an MTU specification
  """

  def __init__(self, name, geom=None):
    self.name = name

    # Get geom
    if geom is None:
      self.geom = self.name.split('=')[0]
    else:
      self.geom = geom

    # Get mesh file also
    filename = f'SITE{self.name}.stl'
    if 'extra' in self.name:
      self.mesh_file = os.path.join(extra_sites_folder, filename)
    else:
      self.mesh_file = os.path.join(asset_folder, filename)


configs = [
  MTU("m.digastricus_L",
         [Site("Skull=m_digastricus_L", "MergedSkull"), Site("Mandible=m_digastricus_L", "Jaw")]),
  MTU("m.digastricus_R",
         [Site("Skull=m_digastricus_R", "MergedSkull"), Site("Mandible=m_digastricus_R", "Jaw")]),
  MTU("m.sternocephalicus_L", [Site("Sternum_1=m_sternocephalicus_L", "Ribcage"),
                                  Site("Skull_=m_sternocephalicus_L", "MergedSkull")]),
  MTU("m.sternocephalicus_R", [Site("Sternum_1=m_sternocephalicus_R", "Ribcage"),
                                  Site("Skull_=m_sternocephalicus_R", "MergedSkull")]),
  MTU("m.brachiocephalicus_L", [Site("humerus_L2=m_brachiocephalicus_", "humerus_L"),
                                   Site("humerus_L1=m_brachiocephalicus_", "humerus_L"),
                                   Site("C_4=m_brachiocephalicus_L_extra_1"),
                                   [[Site("C_2=m_brachiocephalicus_")],
                                    [Site("Skull_1L=m_brachiocephalicus", "MergedSkull")]]],
      mesh_name="m.brachiocephalicus", scale_factor=0.5),
  MTU("m.brachiocephalicus_R", [Site("humerus_R2=m_brachiocephalicus_", "humerus_R"),
                                   Site("humerus_R1=m_brachiocephalicus_", "humerus_R"),
                                   Site("C_4=m_brachiocephalicus_R_extra_1"),
                                   [[Site("C_2=m_brachiocephalicus_")],
                                    [Site("Skull_1R=m_brachiocephalicus", "MergedSkull")]]],
      mesh_name="m.brachiocephalicus", scale_factor=0.5),
  MTU("m.trapezius_L", [Site("Scapula_L=trapezius_extra_1"), Site("Scapula_L=trapezius"),
                           [[Site("Ligament-1=m_trapezius", "C_3")],
                            [Site("Scapula_L=trapezius_extra_3"), Site("Ligament-13=m_trapezius", "Ribcage")]]],
         mesh_name="m.trapezius", scale_factor=0.5),
  MTU("m.trapezius_R", [Site("Scapula_R=trapezius_extra_1"), Site("Scapula_R=trapezius"),
                           [[Site("Ligament-1=m_trapezius", "C_3")],
                            [Site("Scapula_R=trapezius_extra_3"), Site("Ligament-13=m_trapezius", "Ribcage")]]],
         mesh_name="m.trapezius", scale_factor=0.5),
  MTU("m.omotransversarius_L", [Site("Scapula_L=m_omotransversarius_L"),
                                   Site("C_1=m_omotransversarius_L")]),
  MTU("m.omotransversarius_R", [Site("Scapula_R=m_omotransversarius_R"),
                                   Site("C_1=m_omotransversarius_R")]),
  MTU("m.deltoideus_acromialis_L", [Site("Scapula_L=m_deltoideus_acromialis_L"),
                                       Site("humerus_L=m_deltoideus_acromialis_L")]),
  MTU("m.deltoideus_scapularis_L", [Site("Scapula_L=m_deltoideus_scapularis_L_extra_1"),
                                       Site("Scapula_L=m_deltoideus_scapularis_L_extra_2"),
                                       Site("humerus_L=m_deltoideus_scapularis_L")]),
  MTU("m.deltoideus_acromialis_R", [Site("Scapula_R=m_deltoideus_acromialis_R"),
                                       Site("humerus_R=m_deltoideus_acromialis_R")]),
  MTU("m.deltoideus_scapularis_R", [Site("Scapula_R=m_deltoideus_scapularis_R_extra_1"),
                                       Site("Scapula_R=m_deltoideus_scapularis_R_extra_2"),
                                       Site("humerus_R=m_deltoideus_scapularis_R")]),
  MTU("m.biceps_brachii_L", [Site("Scapula_L=m_biceps_brachii_L"),
                                Site("humerus_L=m_biceps_brachii_L_extra_4"),
                                Site("humerus_L=m_biceps_brachii_L_extra_3"),
                                Site("Radius_L=m_biceps_brachii_L")]),
  MTU("m.biceps_brachii_R", [Site("Scapula_R=m_biceps_brachii_R"),
                                Site("humerus_R=m_biceps_brachii_R_extra_4"),
                                Site("humerus_R=m_biceps_brachii_R_extra_3"),
                                Site("Radius_R=m_biceps_brachii_R")]),
  MTU("m.pronator_teres_L",
         [Site("humerus_L=m.pronator_teres_L"), Site("Radius_L=m.pronator_teres_L")]),
  MTU("m.pronator_teres_R",
         [Site("humerus_R=m.pronator_teres_R"), Site("Radius_R=m.pronator_teres_R")]),
  MTU("m.flexor_capri_radialis_L", [Site("humerus_L=m_flexor_capri_radialis_L"),
                                       Site("Carpal_II_L=m_flexor_capri_radialis_L_extra_2"),
                                       [[Site("Os_metacarpale_II_L=m_flexor_capri_radialis_L")],
                                        [Site("Os_metacarpale_III_L=m_flexor_capri_radialis_L")]]]),
  MTU("m.flexor_capri_radialis_R", [Site("humerus_R=m_flexor_capri_radialis_R"),
                                       Site("Carpal_II_R=m_flexor_capri_radialis_R_extra_2"),
                                       [[Site("Os_metacarpale_II_R=m_flexor_capri_radialis_R")],
                                        [Site("Os_metacarpale_III_R=m_flexor_capri_radialis_R")]]]),
  MTU("m.flexor_digitorum_superficialis_L",
         [Site("humerus_L=m_flexor_digitorum_superficialis_L"),
          Site("Carpal_L=m_flexor_digitorum_superficialis_L_extra_1"),
          [[Site("Os_metacarpale_II_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_II_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_II_L=m_flexor_digitorum_superficialis_L_extra_2"),
            Site("Phalanx_distalis_digiti_II_L=m_flexor_digitorum_superficialis_L")],
           [Site("Os_metacarpale_III_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_III_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_III_L=m_flexor_digitorum_superficialis_L_extra_2"),
            Site("Phalanx_distalis_digiti_III_L=m_flexor_digitorum_superficialis_L_extra_1")],
           [Site("Os_metacarpale_IV_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_IV_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_IV_L=m_flexor_digitorum_superficialis_L_extra_2"),
            Site("Phalanx_distalis_digiti_IV_L=m_flexor_digitorum_superficialis_L")],
           [Site("Os_metacarpale_V_L_dot_001=m_flexor_digitorum_superficialis_L_extra_1", "Os_metacarpale_V_L.001"),
            Site("Phalanx_media_digiti_V_L=m_flexor_digitorum_superficialis_L_extra_1"),
            Site("Phalanx_media_digiti_V_L=m_flexor_digitorum_superficialis_L_extra_2"),
            Site("Phalanx_distalis_digiti_V_L=m_flexor_digitorum_superficialis_L")]]]),
  MTU("m.flexor_digitorum_superficialis_R",
         [Site("humerus_R=m_flexor_digitorum_superficialis_R"),
          Site("Carpal_R=m_flexor_digitorum_superficialis_R_extra_1"),
          [[Site("Os_metacarpale_II_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_II_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_II_R=m_flexor_digitorum_superficialis_R_extra_2"),
            Site("Phalanx_distalis_digiti_II_R=m_flexor_digitorum_superficialis_R")],
           [Site("Os_metacarpale_III_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_III_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_III_R=m_flexor_digitorum_superficialis_R_extra_2"),
            Site("Phalanx_distalis_digiti_III_R=m_flexor_digitorum_superficialis_R_extra_1")],
           [Site("Os_metacarpale_IV_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_IV_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_IV_R=m_flexor_digitorum_superficialis_R_extra_2"),
            Site("Phalanx_distalis_digiti_IV_R=m_flexor_digitorum_superficialis_R")],
           [Site("Os_metacarpale_V_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_V_R=m_flexor_digitorum_superficialis_R_extra_1"),
            Site("Phalanx_media_digiti_V_R=m_flexor_digitorum_superficialis_R_extra_2"),
            Site("Phalanx_distalis_digiti_V_R=m_flexor_digitorum_superficialis_R")]]],
      mesh_name="m.flexor_digitorum_superficialis_L"),
  MTU("m.flexor_digitorum_profundus_humerus_L",
         [Site("humerus_L=m_flexor_digitorum_profundus_L"),
          Site("Ulna_L=m_flexor_digitorum_profundus_L_extra_1"),
          Site("Carpal_L=m_flexor_digitorum_profundus_L_extra_1"),
          [[Site("Os_metacarpale_I_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Os_metacarpale_V_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_distalis_digiti_I_L=m_flexor_digitorum_profundus_L")],
           [Site("Os_metacarpale_II_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_II_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_II_L=m_flexor_digitorum_profundus_L_extra_2"),
            Site("Phalanx_distalis_digiti_II_L=m_flexor_digitorum_profundus_L")],
           [Site("Os_metacarpale_III_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_III_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_III_L=m_flexor_digitorum_profundus_L_extra_2"),
            Site("Phalanx_distalis_digiti_III_L=m_flexor_digitorum_profundus_L")],
           [Site("Os_metacarpale_IV_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_IV_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_IV_L=m_flexor_digitorum_profundus_L_extra_2"),
            Site("Phalanx_distalis_digiti_IV_L=m_flexor_digitorum_profundus_L")],
           [Site("Os_metacarpale_V_L_dot_001=m_flexor_digitorum_profundus_L_extra_1",
                 "Os_metacarpale_V_L.001"),
            Site("Phalanx_media_digiti_V_L=m_flexor_digitorum_profundus_L_extra_1"),
            Site("Phalanx_media_digiti_V_L=m_flexor_digitorum_profundus_L_extra_2"),
            Site("Phalanx_distalis_digiti_V_L=m_flexor_digitorum_profundus_L")]]],
      mesh_name="m.flexor_digitorum_profundus_L"),
  MTU("m.flexor_digitorum_profundus_humerus_R",
         [Site("humerus_R=m_flexor_digitorum_profundus_R"),
          Site("Ulna_R=m_flexor_digitorum_profundus_R_extra_1"),
          Site("Carpal_R=m_flexor_digitorum_profundus_R_extra_1"),
          [[Site("Os_metacarpale_I_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Os_metacarpale_V_R_dot_001=m_flexor_digitorum_profundus_R_extra_1",
                 "Os_metacarpale_V_R.001"),
            Site("Phalanx_distalis_digiti_I_R=m_flexor_digitorum_profundus_R")],
           [Site("Os_metacarpale_II_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_II_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_II_R=m_flexor_digitorum_profundus_R_extra_2"),
            Site("Phalanx_distalis_digiti_II_R=m_flexor_digitorum_profundus_R")],
           [Site("Os_metacarpale_III_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_III_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_III_R=m_flexor_digitorum_profundus_R_extra_2"),
            Site("Phalanx_distalis_digiti_III_R=m_flexor_digitorum_profundus_R")],
           [Site("Os_metacarpale_IV_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_IV_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_IV_R=m_flexor_digitorum_profundus_R_extra_2"),
            Site("Phalanx_distalis_digiti_V_R=m_flexor_digitorum_profundus_R.001",
                 "Phalanx_distalis_digiti_IV_R")],
           [Site("Os_metacarpale_V_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_V_R=m_flexor_digitorum_profundus_R_extra_1"),
            Site("Phalanx_media_digiti_V_R=m_flexor_digitorum_profundus_R_extra_2"),
            Site("Phalanx_distalis_digiti_V_R=m_flexor_digitorum_profundus_R")]]],
      mesh_name="m.flexor_digitorum_profundus_R"),
  MTU("m.triceps_brachii_L", [Site("Ulna_L=m_triceps_brachii_L_extra_1"),
                                 Site("humerus_L=m_triceps_brachii_L_extra_1"),
                                 [[Site("Scapula_L=m_triceps_brachii_long_L")],
                                  [Site("humerus_L=m_triceps_brachii_medial_L")],
                                  [Site("humerus_L=m_triceps_brachii_lateral_L")]]],
      mesh_name=["m.triceps_brachii_long_L", "m.triceps_brachii_lateral_L",
                                   "m.triceps_brachii_long_L(2)", "m.triceps_brachii_medial_L",
                                   "m.triceps_brachii_accessory_L"]),
  MTU("m.triceps_brachii_R", [Site("Ulna_R=m_triceps_brachii_R_extra_1"),
                                 Site("humerus_R=m_triceps_brachii_R_extra_1"),
                                 [[Site("Scapula_R=m_triceps_brachii_long_R")],
                                  [Site("humerus_R=m_triceps_brachii_medial_R")],
                                  [Site("humerus_R=m_triceps_brachii_lateral_R")]]],
      mesh_name=["m.triceps_brachii_long_R", "m.triceps_brachii_lateral_L",
                                   "m.triceps_brachii_long_R(2)", "m.triceps_brachii_medial_R",
                                   "m.triceps_brachii_accessory_R"]),
  MTU("m.anconeus_L", [Site("humerus_L=m_anconeus_L"), Site("Ulna_L=m_anconeus_L")]),
  MTU("m.anconeus_R", [Site("humerus_R=m_anconeus_R"), Site("Ulna_R=m_anconeus_R")]),
  MTU("m.coracobrachialis_L", [Site("Scapula_L=m_coracobrachialis_L"),
                                  Site("humerus_L=m_coracobrachialis_L_extra_1"),
                                  Site("humerus_L=m_coracobrachialis_L")]),
  MTU("m.brachialis_L", [Site("humerus_L=m_brachialis_L"), Site("humerus_L=m_brachialis_L_extra_1"),
                            Site("humerus_L=m_brachialis_L_extra_2"), Site("Radius_L=m_brachialis_L_extra_1"),
                            Site("Radius_L=m_brachialis_L")]),
  MTU("m.coracobrachialis_R", [Site("Scapula_R=m_coracobrachialis_R"),
                                  Site("humerus_R=m_coracobrachialis_R_extra_1"),
                                  Site("humerus_R=m_coracobrachialis_R")]),
  MTU("m.brachialis_R", [Site("humerus_R=m_brachialis_R"), Site("humerus_R=m_brachialis_R_extra_1"),
                            Site("humerus_R=m_brachialis_R_extra_2"), Site("Radius_R=m_brachialis_R_extra_1"),
                            Site("Radius_R=m_brachialis_R")]),
  MTU("m_extensor_capri_radialis_L", [Site("humerus_L=m_extensor_capri_radialis_L"),
                                         Site("Carpal_II_L=m_extensor_capri_radialis_L")]),
  MTU("m.extensor_capri_radialis_R", [Site("humerus_R=m_extensor_capri_radialis_R"),
                                         Site("Carpal_II_R=m_extensor_capri_radialis_R")]),
  MTU("m.extensor_capri_ulnaris_L", [Site("humerus_L=m.extensor_capri_ulnaris_L"),
                                        Site("Os_metacarpale_V_L=m.extensor_capri_ulnaris_L", "Os_metacarpale_V_L.001")]),
  MTU("m.extensor_capri_ulnaris_R", [Site("humerus_R=m.extensor_capri_ulnaris_R"),
                                        Site("Os_metacarpale_V_R=m.extensor_capri_ulnaris_R")]),
  MTU("m.supinator_L",
         [Site("humerus_L=m_supinator_L"),
          Site("Radius_L=m_supinator_L_extra_1"),
          Site("Radius_L=m_supinator_L")]),
  MTU("m.supinator_R",
         [Site("humerus_R=m_supinator_R"),
          Site("Radius_R=m_supinator_R_extra_1"),
          Site("Radius_R=m_supinator_R")]),
  MTU("m.extensor_digitorum_lat_R",
         [Site("Ulna_R=m_extensor_digitorum_lat_R"), Site("Radius_R=m_extensor_digitorum_lat_R_extra_1"),
          [[Site("Os_metacarpale_V_R=m_extensor_digitorum_lat_R_extra_1"),
            Site("Phalanxpmxinutlis_digiti_V_R=m_extensor_digitorum_lat_R_extra_1"),
            Site("Phalanx_distalis_digiti_V_R=m_extensor_digitorum_lat_R")],
           [Site("Os_metacarpale_IV_R=m_extensor_digitorum_lat_R_extra_1"),
            [[Site("Os_metacarpale_IV_R=m_extensor_digitorum_lat_R_extra_2"),
              Site("Phalanxpmxinutlis_digiti_IV_R=m_extensor_digitorum_lat_R_extra_1"),
              Site("Phalanx_distalis_digiti_IV_R=m_extensor_digitorum_lat_R")],
             [Site("Os_metacarpale_III_R=m_extensor_digitorum_lat_R_extra_1"),
              Site("Phalanxpmxinutlis_digiti_III_R=m_extensor_digitorum_lat_R_extra_1"),
              Site("Phalanx_distalis_digiti_III_R=m_extensor_digitorum_lat_R")]]]]]),
  MTU("m.extensor_digitorum_communis_R",
         [Site("humerus_R=m_extensor_digitorum_communis_R"),
          Site("Radius_R=m_extensor_digitorum_communis_R_extra_1"),
          [[Site("Os_metacarpale_V_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanxpmxinutlis_digiti_V_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanx_distalis_digiti_V_R=m_extensor_digitorum_communis_R")],
           [Site("Os_metacarpale_IV_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanxpmxinutlis_digiti_IV_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanx_distalis_digiti_IV_R=m_extensor_digitorum_communis_R")],
           [Site("Os_metacarpale_III_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanxpmxinutlis_digiti_III_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanx_distalis_digiti_III_R=m_extensor_digitorum_communis_R")],
           [Site("Os_metacarpale_II_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanxpmxinutlis_digiti_II_R=m_extensor_digitorum_communis_R_extra_1"),
            Site("Phalanx_distalis_digiti_II_R=m_extensor_digitorum_communis_R")]]]),
  MTU("m_extensor_digitorum_lat_L",
         [Site("Ulna_L=m_extensor_digitorum_lat_L"), Site("Radius_L=m_extensor_digitorum_lat_L_extra_1"),
          [[Site("Os_metacarpale_V_L_dot_001=m_extensor_digitorum_lat_L_extra_1",
                 "Os_metacarpale_V_L.001"),
            Site("Phalanxpmxinutlis_digiti_V_L=m_extensor_digitorum_lat_L_extra_1"),
            Site("Phalanx_distalis_digiti_V_L=m_extensor_digitorum_lat_L")],
           [Site("Os_metacarpale_IV_L=m_extensor_digitorum_lat_L_extra_1"),
            [[Site("Os_metacarpale_IV_L=m_extensor_digitorum_lat_L_extra_2"),
              Site("Phalanxpmxinutlis_digiti_IV_L_=m_extensor_digitorum_lat_L_extra_1"),
              Site("Phalanx_distalis_digiti_IV_L=m_extensor_digitorum_lat_L")],
             [Site("Os_metacarpale_III_L=m_extensor_digitorum_lat_L_extra_1"),
              Site("Phalanxpmxinutlis_digiti_III_L_=m_extensor_digitorum_lat_L_extra_1"),
              Site("Phalanx_distalis_digiti_III_L=m_extensor_digitorum_lat_L")]]]]]),
  MTU("m.extensor_digitorum_communis_L",
         [Site("humerus_L=m_extensor_digitorum_communis_L"),
          Site("Radius_L=m_extensor_digitorum_communis_L_extra_1"),
          [[Site("Os_metacarpale_V_L_dot_001=m_extensor_digitorum_communis_L_extra_1",
                 "Os_metacarpale_V_L.001"),
            Site("Phalanxpmxinutlis_digiti_V_L=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanx_distalis_digiti_V_L=m_extensor_digitorum_communis_L")],
           [Site("Os_metacarpale_IV_L=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanxpmxinutlis_digiti_IV_L_=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanx_distalis_digiti_IV_L=m_extensor_digitorum_communis_L")],
           [Site("Os_metacarpale_III_L=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanxpmxinutlis_digiti_III_L_=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanx_distalis_digiti_III_L=m_extensor_digitorum_communis_L")],
           [Site("Os_metacarpale_II_L=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanxpmxinutlis_digiti_II_L=m_extensor_digitorum_communis_L_extra_1"),
            Site("Phalanx_distalis_digiti_II_L=m_extensor_digitorum_communis_L")]]]),
  MTU("m.latissimus_dors_L", [Site("humerus_L=m_latissimus_dors"),
                                          Site("humerus_L=m_latissimus_dors_L_extra_1"),
                                          [[Site("Scapula_L=m_latissimus_dors_L_extra_1"),
                                            Site("T_6=m_latissimus_dors_L_extra_1", "Ribcage")],
                                           [Site("Rib_L_7=m_latissimus_dors_L_extra_1", "Ribcage"),
                                            Site("Rib_L_12=m_latissimus_dors", "Ribcage")]]]),
  MTU("m.latissimus_dors_R", [Site("humerus_R=m_latissimus_dors"),
                                          Site("humerus_R=m_latissimus_dors_R_extra_1"),
                                          [[Site("Scapula_R=m_latissimus_dors_R_extra_1"),
                                            Site("T_6=m_latissimus_dors_R_extra_1", "Ribcage")],
                                           [Site("Rib_R_7=m_latissimus_dors_R_extra_1", "Ribcage"),
                                            Site("Rib_R_12=m_latissimus_dors", "Ribcage")]]]),
  MTU("m.pectorales_superficiales_1_L",
         [Site("humerus_L=m_pectorales_superficiales_1"),
          Site("Sternum_2=m_pectorales_superficiales_1", "Ribcage")],
      mesh_name=["m.pectorales_superficiales_1", "m.pectorales_superficiales_2"], scale_factor=0.5),
  MTU("m.pectorales_superficiales_1_R",
         [Site("humerus_R=m_pectorales_superficiales_1"),
          Site("Sternum_2=m_pectorales_superficiales_1", "Ribcage")],
      mesh_name=["m.pectorales_superficiales_1", "m.pectorales_superficiales_2"], scale_factor=0.5),
  MTU("mm.thoracis_m.pectoralis_profundus_L",
         [Site("humerus_L=mm_thoracis_m_pectoralis_profundus"),
          Site("Rib_L_1=mm_thoracis_m_pectoralis_profundus", "Ribcage"),
          [[Site("Sternum_1=mm_thoracis_m_pectoralis_profundus", "Ribcage")],
           [Site("Sternum_3=mm_thoracis_m_pectoralis_profundus", "Ribcage")],
           [Site("Rib_L_4=mm_thoracis_m_pectoralis_profundus", "Ribcage")]]],
      mesh_name="mm.thoracis_m.pectoralis_profundus", scale_factor=0.5),
  MTU("mm.thoracis_m.pectoralis_profundus_R",
         [Site("humerus_R=mm_thoracis_m_pectoralis_profundus"),
          Site("Rib_R_1=mm_thoracis_m_pectoralis_profundus", "Ribcage"),
          [[Site("Sternum_1=mm_thoracis_m_pectoralis_profundus", "Ribcage")],
           [Site("Sternum_3=mm_thoracis_m_pectoralis_profundus", "Ribcage")],
           [Site("Rib_R_4=mm_thoracis_m_pectoralis_profundus", "Ribcage")]]],
      mesh_name="mm.thoracis_m.pectoralis_profundus", scale_factor=0.5),
  MTU("m.obliquus_int_abdominis_L",
         [Site("Pelvis=m_obliquus_int_abdominis_L"), Site("Pelvis=m_obliquus_int_abdominis_L_extra_1"),
          [[Site("Rib_L_12=m_obliquus_int_abdominis_L", "Ribcage")],
           [Site("Rib_L_13=m_obliquus_int_abdominis_L", "Ribcage")]]]),
  MTU("m.obliquus_int_abdominis_R",
         [Site("Pelvis=m_obliquus_int_abdominis_R"), Site("Pelvis=m_obliquus_int_abdominis_R_extra_1"),
          [[Site("Rib_R_12=m_obliquus_int_abdominis_R", "Ribcage")],
           [Site("Rib_R_13=m_obliquus_int_abdominis_R", "Ribcage")]]]),
  MTU("m.obliquus_ext_abdominis_L",
         [Site("Pelvis=Mm_abdominis_m.obliquus_ext._abdominis_L"),
          Site("Pelvis=m_obliquus_int_abdominis_L_extra_1"),
          [[Site("Rib_L_13=Mm_abdominis_m.obliquus_ext._abdominis_L", "Ribcage")],
           [Site("Rib_L_10=Mm_abdominis_m.obliquus_ext._abdominis_L", "Ribcage")],
           [Site("Rib_L_8=Mm_abdominis_m.obliquus_ext._abdominis_L", "Ribcage")],
           [Site("Rib_L_5=Mm_abdominis_m.obliquus_ext._abdominis_L", "Ribcage")]]]),
  MTU("m.obliquus_ext_abdominis_R",
         [Site("Pelvis=Mm_abdominis_m.obliquus_ext._abdominis_R"),
          Site("Pelvis=m_obliquus_int_abdominis_R_extra_1"),
          [[Site("Rib_R_13=Mm_abdominis_m.obliquus_ext._abdominis_R", "Ribcage")],
           [Site("Rib_R_10=Mm_abdominis_m.obliquus_ext._abdominis_R", "Ribcage")],
           [Site("Rib_R_8=Mm_abdominis_m.obliquus_ext._abdominis_R", "Ribcage")],
           [Site("Rib_R_5=Mm_abdominis_m.obliquus_ext._abdominis_R", "Ribcage")]]]),
  MTU("m.gluteus_medius_L",
         [Site("Pelvis=m_gluteus_medius_L"), Site("Femoris_L=m_gluteus_medius_L_extra_1")]),
  MTU("m.gluteus_medius_R",
         [Site("Pelvis=m_gluteus_medius_R"), Site("Femoris_R=m_gluteus_medius_R_extra_1")]),
  MTU("m.gluteus_profundus_minor_L", [Site("Pelvis=m_gluteus_profundus_minor_L_extra_1"),
                                         Site("Femoris_L=m_gluteus_profundus_minor_L")]),
  MTU("m.gluteus_profundus_minor_R", [Site("Pelvis=m_gluteus_profundus_minor_R_extra_1"),
                                         Site("Femoris_R=m_gluteus_profundus_minor_R")]),
  MTU("m.gluteus_superficialis_major_L",
         [Site("Sacrum=m_gluteus_superficialis_major_L"),
          Site("Femoris_L=m_gluteus_superficialis_major_L_extra_2"),
          Site("Femoris_L=m_gluteus_superficialis_major_L_extra_1")]),
  MTU("m.gluteus_superficialis_major_R",
         [Site("Sacrum=m_gluteus_superficialis_major_R"),
          Site("Femoris_R=m_gluteus_superficialis_major_R_extra_2"),
          Site("Femoris_R=m_gluteus_superficialis_major_R_extra_1")]),
  MTU("m.sartorius_L",
         [Site("Pelvis=m_sartorius_L_extra_1"), Site("Pelvis=m_sartorius_L(2)"),
          [[Site("Patella_L=m_sartorius_L(2)")],
           [Site("Femoris_L=m_sartorius_L_extra_1"), Site("Tibia_L=m_sartorius_L")]]],
      mesh_name=["m.sartorius_L", "m.sartorius_L(2)"]),
  MTU("m.sartorius_R",
         [Site("Pelvis=m_sartorius_R_extra_1"), Site("Pelvis=m_sartorius_R(2)"),
          [[Site("Patella_R=m_sartorius_R(2)")],
           [Site("Femoris_R=m_sartorius_R_extra_1"), Site("Tibia_R=m_sartorius_R")]]],
      mesh_name=["m.sartorius_R", "m.sartorius_R(2)"]),
  MTU("m_tensor_f.latae_L",
         [Site("Pelvis=m_tensor_f.latae_L"),
          Site("Femoris_L=m_tensor_f_latae_L_extra_1")]),
  MTU("m_tensor_f.latae_R",
         [Site("Pelvis=m_tensor_f.latae_R"),
          Site("Femoris_R=m_tensor_f_latae_R_extra_1")]),
  MTU("m.tensor_f.antebrachii_L",
         [Site("Rib_L_3=m_tensor_f_antebrachii_L_extra_1", "Ribcage"), Site("Ulna_L=m_tensor_f.antebrachii_L")]),
  MTU("m.tensor_f.antebrachii_R",
         [Site("Rib_R_3=m_tensor_f_antebrachii_R_extra_1", "Ribcage"), Site("Ulna_R=m_tensor_f.antebrachii_R")]),
  MTU("m.semitendinosus_L",
         [Site("Pelvis=m_semitendinosus_L"), Site("Tibia_L=m_semitendinosus_L_extra_1"),
          Site("Tibia_L=m_semitendinosus_L")]),
  MTU("m.semitendinosus_R",
         [Site("Pelvis=m_semitendinosus_R"), Site("Tibia_R=m_semitendinosus_R_extra_1"),
          Site("Tibia_R=m_semitendinosus_R")]),
  MTU("m.semimembranosus_L", [Site("Pelvis=m_semimembranosus_L_"),
                                 Site("Femoris_fabellae_L_2=m_semimembranosus_L_")]),
  MTU("m.semimembranosus_R", [Site("Pelvis=m_semimembranosus_R"),
                                 Site("Femoris_fabellae_R_2=m_semimembranosus_R")]),
  MTU("m_biceps_femoris_L",
         [Site("sacrotuberous_lig_L=m_biceps_femoris_L", "Pelvis"), Site("Pelvis=m_biceps_femoris_L_extra_1"),
          Site("Femoris_L=m_biceps_femoris_L_extra_1"), Site("Tibia_L=m_biceps_femoris_L_extra_1")]),
  MTU("m_biceps_femoris_R",
         [Site("sacrotuberous_lig_R=m_biceps_femoris_R", "Pelvis"), Site("Pelvis=m_biceps_femoris_R_extra_1"),
          Site("Femoris_R=m_biceps_femoris_R_extra_1"), Site("Tibia_R=m_biceps_femoris_R_extra_1")]),
  MTU("m.gracilis_L", [Site("Pelvis=m_gracilis_L"), Site("Tibia_L=m_gracilis_L")]),
  MTU("m.gracilis_R", [Site("Pelvis=m_gracilis_R"), Site("Tibia_R=m_gracilis_R")]),
  MTU("m.gastrocnemius_L", [Site("Calcaneal_tuber_L=m_gastrocnemius_L"),
                               Site("Femoris_L1=m_gastrocnemius_L", "Femoris_L")]),
  MTU("m.gastrocnemius_R", [Site("Calcaneal_tuber_R=m_gastrocnemius_R"),
                               Site("Femoris_R1=m_gastrocnemius_R", "Femoris_R")]),
  MTU("m.tibialis_caudalis_L",
         [Site("ibula_L=m_tibialis_caudalis_L.001", "Tibia_L"), Site("Tibia_L=m_tibialis_caudalis_L_extra_1"),
          Site("ibula_L=m_tibialis_caudalis_L", "Tibial_tarsal_L")]),
  MTU("m.tibialis_caudalis_R",
         [Site("ibula_R=m_tibialis_caudalis_R.001", "Tibia_R"), Site("Tibia_R=m_tibialis_caudalis_R_extra_1"),
          Site("ibula_R=m_tibialis_caudalis_R", "Tibial_tarsal_R")]),
  MTU("m.tibialis_cranialis_L",
         [Site("Fibula_L=m_tibialis_cranialis_L"), Site("Tibia_L=m_tibialis_cranialis_L_extra_1"),
          Site("Tarsus_central_L=m_tibialis_cranialis_L")]),
  MTU("m.tibialis_cranialis_R",
         [Site("Fibula_R=m_tibialis_cranialis_R"), Site("Tibia_R=m_tibialis_cranialis_R_extra_1"),
          Site("Tarsus_central_R=m_tibialis_cranialis_R")]),
  MTU("m.adductor_longus_L",
         [Site("Pelvis=m_adductor_longus_L"), Site("Femoris_L=m_adductor_longus_L")]),
  MTU("m.adductor_longus_R",
         [Site("Pelvis=m_adductor_longus_R"), Site("Femoris_R=m_adductor_longus_R")]),
  MTU("m.longus_capitis_L",
         [Site("T-3=m_longus_capitis_L", "Ribcage"), Site("T-2=m_longus_capitis_L", "Ribcage"),
          Site("T-1=m_longus_capitis_L", "Ribcage"), Site("C_7=m_longus_capitis_L"),
          Site("C_4=m_longus_capitis_L"),
          Site("C_3=m_longus_capitis_L"), Site("Skull_=m_longus_capitis_L", "MergedSkull")]),
  MTU("m.longus_capitis_R",
         [Site("T-3=m_longus_capitis_R", "Ribcage"), Site("T-2=m_longus_capitis_R", "Ribcage"),
          Site("T-1=m_longus_capitis_R", "Ribcage"), Site("C_7=m_longus_capitis_R"),
          Site("C_4=m_longus_capitis_R"),
          Site("C_3=m_longus_capitis_R"), Site("Skull_=m_longus_capitis_R", "MergedSkull")]),
  MTU("m.abductor_pollicis_longus_L",
         [Site("Radius_L=m_abductor_pollicis_longus_L"), Site("Radius_L=m_abductor_pollicis_longus_L_extra_1"),
          Site("Carpal_L=m_abductor_pollicis_longus_L_extra_1"),
          Site("Os_metacarpale_I_L=m_abductor_pollicis_longus_L")]),
  MTU("m.abductor_pollicis_longus_R",
         [Site("Radius_R=m_abductor_pollicis_longus_R"), Site("Radius_R=m_abductor_pollicis_longus_R_extra_1"),
          Site("Carpal_R=m_abductor_pollicis_longus_R_extra_1"),
          Site("Os_metacarpale_I_R=m_abductor_pollicis_longus_R")]),
  MTU("m.peroneus_longus_L",
         [Site("Tibia_L=m_peroneus_longus_L"), Site("Tibia_L=m_peroneus_longus_L_extra_1"),
          Site("Tarsus_L_IV=m_peroneus_longus_L_extra_1"), Site("Tarsus_L_I=m_peroneus_longus_L")]),
  MTU("m.peroneus_longus_R",
         [Site("Tibia_R=m_peroneus_longus_R"), Site("Tibia_R=m_peroneus_longus_R_extra_1"),
          Site("Tarsus_R_IV=m_peroneus_longus_R_extra_1"), Site("Tarsus_R_I=m_peroneus_longus_R")]),
  MTU("m.peroneus_brevis_L",
         [Site("Fibula_L=m_peroneus_brevis_L"), Site("Fibula_L=m_peroneus_brevis_L_extra_1"),
          Site("Metatarsi_L_4=m_peroneus_brevis_L")]),
  MTU("m.peroneus_brevis_R",
         [Site("Fibula_R=m_peroneus_brevis_R"), Site("Fibula_R=m_peroneus_brevis_R_extra_1"),
          Site("Metatarsi_R_4=m_peroneus_brevis_R")]),
  MTU("m.extensor_digitorum_longus_L",
      [Site("Femoris_L=m_extensor_digitorum_longus_L"),
       Site("Femoris_L=m_extensor_digitorum_longus_L_extra_1"),
       Site("Tibia_L=m_extensor_digitorum_longus_L_extra_1"),
       Site("Tarsus_central_L=m_extensor_digitorum_longus_L_extra_1"),
       [[Site("Phalanges_B_L_1=m_extensor_digitorum_longus_L_extra_2"),
         Site("Phalanges_B_L_1=m_extensor_digitorum_longus_L_extra_1"),
         Site("Phalanges_B_3_L_1=m_extensor_digitorum_longus_L")],
        [Site("Phalanges_B_L_2=m_extensor_digitorum_longus_L_extra_2"),
         Site("Phalanges_B_L_2=m_extensor_digitorum_longus_L_extra_1"),
         Site("Phalanges_B_3_L_2=m_extensor_digitorum_longus_L")],
        [Site("Phalanges_B_L_3=m_extensor_digitorum_longus_L_extra_2"),
         Site("Phalanges_B_L_3=m_extensor_digitorum_longus_L_extra_1"),
         Site("Phalanges_B_3_L_3=m_extensor_digitorum_longus_L")],
        [Site("Phalanges_B_L_4=m_extensor_digitorum_longus_L_extra_2"),
         Site("Phalanges_B_L_4=m_extensor_digitorum_longus_L_extra_1"),
         Site("Phalanges_B_3_L_4=m_extensor_digitorum_longus_L")]]]),
  MTU("m.extensor_digitorum_longus_R",
      [Site("Femoris_R=m_extensor_digitorum_longus_R"),
       Site("Femoris_R=m_extensor_digitorum_longus_R_extra_1"),
       Site("Tibia_R=m_extensor_digitorum_longus_R_extra_1"),
       Site("Tarsus_central_R=m_extensor_digitorum_longus_R_extra_1"),
       [[Site("Phalanges_B_R_1=m_extensor_digitorum_longus_R_extra_2"),
         Site("Phalanges_B_R_1=m_extensor_digitorum_longus_R_extra_1"),
         Site("Phalanges_B_3_R_1=m_extensor_digitorum_longus_R")],
        [Site("Phalanges_B_R_2=m_extensor_digitorum_longus_R_extra_2"),
         Site("Phalanges_B_R_2=m_extensor_digitorum_longus_R_extra_1"),
         Site("Phalanges_B_3_R_2=m_extensor_digitorum_longus_R")],
        [Site("Phalanges_B_R_3=m_extensor_digitorum_longus_R_extra_2"),
         Site("Phalanges_B_R_3=m_extensor_digitorum_longus_R_extra_1"),
         Site("Phalanges_B_3_R_3=m_extensor_digitorum_longus_R")],
        [Site("Phalanges_B_R_4=m_extensor_digitorum_longus_R_extra_2"),
         Site("Phalanges_B_R_4=m_extensor_digitorum_longus_R_extra_1"),
         Site("Phalanges_B_3_R_4=m_extensor_digitorum_longus_R")]]]),
  MTU("m.flexor_digitorum_profundus_L(2)",
         [Site("Tibia_L=m_flexor_digitorum_profundus_L(2)_extra_2"),
          Site("Tibia_L=m_flexor_digitorum_profundus_L(2)_extra_1"),
          Site("Tarsus_central_L=m_flexor_digitorum_profundus_L(2)_extra_1"),
          [[Site("Phalanges_B_L_1=m_flexor_digitorum_profundus_L(2)_extra_2"),
            Site("Phalanges_B_L_1=m_flexor_digitorum_profundus_L(2)_extra_1"),
            Site("Phalanges_B_3_L_1=m_flexor_digitorum_profundus_L")],
           [Site("Phalanges_B_L_2=m_flexor_digitorum_profundus_L(2)_extra_2"),
            Site("Phalanges_B_L_2=m_flexor_digitorum_profundus_L(2)_extra_1"),
            Site("Phalanges_B_3_L_2=m_flexor_digitorum_profundus_L")],
           [Site("Phalanges_B_L_3=m_flexor_digitorum_profundus_L(2)_extra_2"),
            Site("Phalanges_B_L_3=m_flexor_digitorum_profundus_L(2)_extra_1"),
            Site("Phalanges_B_3_L_3=m_flexor_digitorum_profundus_L")],
           [Site("Phalanges_B_L_4=m_flexor_digitorum_profundus_L(2)_extra_2"),
            Site("Phalanges_B_L_4=m_flexor_digitorum_profundus_L(2)_extra_1"),
            Site("Phalanges_B_3_L_4=m_flexor_digitorum_profundus_L")]]]),
  MTU("m.flexor_digitorum_profundus_R(2)",
         [Site("Tibia_R=m_flexor_digitorum_profundus_R(2)_extra_2"),
          Site("Tibia_R=m_flexor_digitorum_profundus_R(2)_extra_1"),
          Site("Tarsus_central_R=m_flexor_digitorum_profundus_R(2)_extra_1"),
          [[Site("Phalanges_B_R_1=m_flexor_digitorum_profundus_R(2)_extra_2"),
            Site("Phalanges_B_R_1=m_flexor_digitorum_profundus_R(2)_extra_1"),
            Site("Phalanges_B_3_R_1=m_flexor_digitorum_profundus_R")],
           [Site("Phalanges_B_R_2=m_flexor_digitorum_profundus_R(2)_extra_2"),
            Site("Phalanges_B_R_2=m_flexor_digitorum_profundus_R(2)_extra_1"),
            Site("Phalanges_B_3_R_2=m_flexor_digitorum_profundus_R")],
           [Site("Phalanges_B_R_3=m_flexor_digitorum_profundus_R(2)_extra_2"),
            Site("Phalanges_B_R_3=m_flexor_digitorum_profundus_R(2)_extra_1"),
            Site("Phalanges_B_3_R_3=m_flexor_digitorum_profundus_R")],
           [Site("Phalanges_B_R_4=m_flexor_digitorum_profundus_R(2)_extra_2"),
            Site("Phalanges_B_R_4=m_flexor_digitorum_profundus_R(2)_extra_1"),
            Site("Phalanges_B_3_R_4=m_flexor_digitorum_profundus_R")]]]),
  MTU("m.rectus_capitis_ventr_L", [Site("C-1=m_rectus_capitis_ventr_L", "C_1"),
                                      Site("Skull_=m_rectus_capitis_ventr_L", "MergedSkull")]),
  MTU("m.rectus_capitis_ventr_R", [Site("C-1=m_rectus_capitis_ventr_R", "C_1"),
                                      Site("Skull_=m_rectus_capitis_ventr_R", "MergedSkull")]),
  MTU("m.rectus_capitis_lateralis_L", [Site("C-1=m_rectus_capitis_lateralis_L", "C_1"),
                                          Site("Skull_=m_rectus_capitis_lateralis_L", "MergedSkull")]),
  MTU("m.rectus_capitis_lateralis_R", [Site("C-1=m_rectus_capitis_lateralis_R", "C_1"),
                                          Site("Skull_=m_rectus_capitis_lateralis_R", "MergedSkull")]),
  MTU("m.extensor_digitorum_lateralis_L",
         [Site("Fibula_L=m_extensor_digitorum_lateralis_L"),
          Site("Fibula_L=m_extensor_digitorum_lateralis_L_extra_1"),
          Site("Phalanges_B_L_4=m_extensor_digitorum_lateralis_L")]),
  MTU("m.extensor_digitorum_lateralis_R",
         [Site("Fibula_R=m_extensor_digitorum_lateralis_R"),
          Site("Fibula_R=m_extensor_digitorum_lateralis_R_extra_1"),
          Site("Phalanges_B_R_4=m_extensor_digitorum_lateralis_R")]),
  MTU("m.longissimus_capitis_L",
         [Site("Pelvis=m_longissimus_capitis_L"), Site("L_4=m_longissimus_capitis_L"),
          Site("Rib_L_7=m_longissimus_capitis_L", "Ribcage"), Site("Rib_L_2=m_longissimus_capitis_L", "Ribcage"),
          Site("T_1=m_longissimus_capitis_L", "Ribcage"), Site("C_3=m_longissimus_capitis_L"),
          Site("Skull_=m_longissimus_capitis_L", "MergedSkull")]),
  MTU("m.longissimus_capitis_R",
         [Site("Pelvis=m_longissimus_capitis_R"), Site("L_4=m_longissimus_capitis_R"),
          Site("Rib_R_7=m_longissimus_capitis_R", "Ribcage"), Site("Rib_R_2=m_longissimus_capitis_R", "Ribcage"),
          Site("T_1=m_longissimus_capitis_R", "Ribcage"), Site("C_3=m_longissimus_capitis_R"),
          Site("Skull_=m_longissimus_capitis_R", "MergedSkull")],
      mesh_name="m.longissimus_capitis_L"),
  MTU("m.longissimus_cervicis_L",
         [Site("T-6=m.longissimus_cervicis_L", "Ribcage"), Site("T_4=m_longissimus_cervicis_L_extra_1", "Ribcage"),
          [[Site("C-3=m.longissimus_cervicis_L", "C_3")], [Site("C-4=m.longissimus_cervicis_L", "C_4")],
           [Site("C-5=m.longissimus_cervicis_L", "C_5")], [Site("C-6=m.longissimus_cervicis_L", "C_6")]]]),
  MTU("m.longissimus_cervicis_R",
         [Site("T-6=m.longissimus_cervicis_R", "Ribcage"), Site("T_4=m_longissimus_cervicis_R_extra_1", "Ribcage"),
          [[Site("C-3=m.longissimus_cervicis_R", "C_3")], [Site("C-4=m.longissimus_cervicis_R", "C_4")],
           [Site("C-5=m.longissimus_cervicis_R", "C_5")], [Site("C-6=m.longissimus_cervicis_R", "C_6")]]]),
  MTU("m.longissimus_thoracis_L",
         [Site("L_1=m_longissimus_thoracis_L"), Site("C_7=m_longissimus_thoracis_L")]),
  MTU("m.longissimus_thoracis_R",
         [Site("L_1=m_longissimus_thoracis_R"), Site("C_7=m_longissimus_thoracis_R")]),
  MTU("m.longissimus__lumborum_L",
         [Site("T_9=m_longissimus_lumborum_L", "Ribcage"), Site("L_3=m_longissimus_lumborum_L"),
          Site("L_6=m_longissimus_lumborum_L"),
          [[Site("Pelvis=m_longissimus_lumborum_L")], [Site("Sacrum=m_longissimus_lumborum_L")]]]),
  MTU("m.longissimus__lumborum_R",
         [Site("T_9=m_longissimus_lumborum_R", "Ribcage"), Site("L_3=m_longissimus_lumborum_R"),
          Site("L_6=m_longissimus_lumborum_R"),
          [[Site("Pelvis=m_longissimus_lumborum_R")], [Site("Sacrum=m_longissimus_lumborum_R")]]]),
  MTU("m.temporalis_L", [Site("Skull_1=m_temporalis_L", "MergedSkull"), Site("Mandible=m_temporalis_L", "Jaw")]),
  MTU("m.temporalis_R", [Site("Skull_1=m_temporalis_R", "MergedSkull"), Site("Mandible=m_temporalis_R", "Jaw")]),
  MTU("m.masseter_L", [Site("Mandible=m_masseter_L_extra_1", "Jaw"), Site("Skull_2=m_masseter_L", "MergedSkull")]),
  MTU("m.masseter_R", [Site("Mandible=m_masseter_R_extra_1", "Jaw"), Site("Skull_2=m_masseter_R", "MergedSkull")]),
  MTU("m.pectineus_L", [Site("Pelvis=m_pectineus_L"), Site("Femoris_L=m_pectineus_L")]),
  MTU("m.pectineus_R", [Site("Pelvis=m_pectineus_R"), Site("Femoris_R=m_pectineus_R")]),
  MTU("m.adductor_magnus_L", [Site("Pelvis=m_adductor_magnus_L"), Site("Femoris_L=m_adductor_magnus_L")]),
  MTU("m.adductor_magnus_R", [Site("Pelvis=m_adductor_magnus_R"), Site("Femoris_R=m_adductor_magnus_R")]),
  MTU("m.obturatorius_ext_L", [Site("Pelvis=m_obturatorius_ext_L"), Site("Femoris_L=m_obturatorius_ext_L")]),
  MTU("m.obturatorius_int_L",
         [Site("Pelvis=m_obturatorius_int_L"), Site("Pelvis=m_obturatorius_int_L_extra_1"),
          Site("Femoris_L=m_obturatorius_int_L")]),
  MTU("m.obturatorius_ext_R", [Site("Pelvis=m_obturatorius_ext_R"), Site("Femoris_R=m_obturatorius_ext_R")]),
  MTU("m.obturatorius_int_R",
         [Site("Pelvis=m_obturatorius_int_R"), Site("Pelvis=m_obturatorius_int_R_extra_1"),
          Site("Femoris_R=m_obturatorius_int_R")]),
  MTU("Mm.thoracis_serratus_ventr_L",
      [Site("Rib_L_7=Mm_thoracis_serratus_ventr_L", "Ribcage"), Site("Scapula_L=Mm_thoracis_serratus_ventr_L"),
       [[Site("C_3=Mm_thoracis_serratus_ventr_L")], [Site("C_4=Mm_thoracis_serratus_ventr_L")],
        [Site("C_5=Mm_thoracis_serratus_ventr_L")], [Site("C_6=Mm_thoracis_serratus_ventr_L")]]]),
  MTU("Mm.thoracis_serratus_ventr_R",
      [Site("Rib_R_7=Mm_thoracis_serratus_ventr_R", "Ribcage"),
       Site("Scapula_L=Mm_thoracis_serratus_ventr_R", "Scapula_R"),
       [[Site("C_3=Mm_thoracis_serratus_ventr_R")], [Site("C_4=Mm_thoracis_serratus_ventr_R")],
        [Site("C_5=Mm_thoracis_serratus_ventr_R")], [Site("C_6=Mm_thoracis_serratus_ventr_R")]]]),
  MTU("m.rectus_capitis_dorsalis_minor_L",
      [Site("C-1=m_rectus_capitis_dorsalis_minor_L", "C_1"),
       Site("Skull_=m_rectus_capitis_dorsalis_minor_L", "MergedSkull")]),
  MTU("m.rectus_capitis_dorsalis_minor_R",
      [Site("C-1=m_rectus_capitis_dorsalis_minor_R", "C_1"),
       Site("Skull_=m_rectus_capitis_dorsalis_minor_R", "MergedSkull")]),
  MTU("m.rectus_capitis_dorsalis_major_L",
      [Site("C_2=m_rectus_capitis_dorsalis_major_L"),
       Site("Skull_=m_rectus_capitis_dorsalis_major_L", "MergedSkull")]),
  MTU("m.rectus_capitis_dorsalis_major_R",
      [Site("C_2=m_rectus_capitis_dorsalis_major_R"),
       Site("Skull_=m_rectus_capitis_dorsalis_major_R", "MergedSkull")]),
  MTU("m.depressor_caudae_brevis_L",
      [Site("Sacrum=m_depressor_caudae_brevis_L"), Site("Ca_1=m_depressor_caudae_brevis_L"),
       Site("Ca_2=m_depressor_caudae_brevis_L"), Site("Ca_4=m_depressor_caudae_brevis_L"),
       Site("Ca_6=m_depressor_caudae_brevis_L"), Site("Ca_8=m_depressor_caudae_brevis_L"),
       Site("Ca_10=m_depressor_caudae_brevis_L"), Site("Ca_12=m_depressor_caudae_brevis_L"),
       Site("Ca_14=m_depressor_caudae_brevis_L"), Site("Ca_16=m_depressor_caudae_brevis_L"),
       Site("Ca_18=m_depressor_caudae_brevis_L"), Site("Ca_20=m_depressor_caudae_brevis_L")]),
  MTU("m.depressor_caudae_brevis_R",
      [Site("Sacrum=m_depressor_caudae_brevis_R"), Site("Ca_1=m_depressor_caudae_brevis_R"),
       Site("Ca_2=m_depressor_caudae_brevis_R"), Site("Ca_4=m_depressor_caudae_brevis_R"),
       Site("Ca_6=m_depressor_caudae_brevis_R"), Site("Ca_8=m_depressor_caudae_brevis_R"),
       Site("Ca_10=m_depressor_caudae_brevis_R"), Site("Ca_12=m_depressor_caudae_brevis_R"),
       Site("Ca_14=m_depressor_caudae_brevis_R"), Site("Ca_16=m_depressor_caudae_brevis_R"),
       Site("Ca_18=m_depressor_caudae_brevis_R"), Site("Ca_20=m_depressor_caudae_brevis_R")]),
  MTU("m.depressor_caudae_brevis_L2",
      [Site("Sacrum=m_depressor_caudae_brevis_L2"), Site("L_7=m_depressor_caudae_brevis_L2"),
       Site("Ca_1=m_depressor_caudae_brevis_L2"),
       Site("Ca_2=m_depressor_caudae_brevis_L2"), Site("Ca_4=m_depressor_caudae_brevis_L2"),
       Site("Ca_6=m_depressor_caudae_brevis_L2"), Site("Ca_8=m_depressor_caudae_brevis_L2"),
       Site("Ca_10=m_depressor_caudae_brevis_L2"), Site("Ca_12=m_depressor_caudae_brevis_L2"),
       Site("Ca_14=m_depressor_caudae_brevis_L2"), Site("Ca_16=m_depressor_caudae_brevis_L2"),
       Site("Ca_18=m_depressor_caudae_brevis_L2"), Site("Ca_20=m_depressor_caudae_brevis_L2")]),
  MTU("m.depressor_caudae_brevis_R2",
      [Site("Sacrum=m_depressor_caudae_brevis_R2"), Site("L_7=m_depressor_caudae_brevis_R2"),
       Site("Ca_1=m_depressor_caudae_brevis_R2"),
       Site("Ca_2=m_depressor_caudae_brevis_R2"), Site("Ca_4=m_depressor_caudae_brevis_R2"),
       Site("Ca_6=m_depressor_caudae_brevis_R2"), Site("Ca_8=m_depressor_caudae_brevis_R2"),
       Site("Ca_10=m_depressor_caudae_brevis_R2"), Site("Ca_12=m_depressor_caudae_brevis_R2"),
       Site("Ca_14=m_depressor_caudae_brevis_R2"), Site("Ca_16=m_depressor_caudae_brevis_R2"),
       Site("Ca_18=m_depressor_caudae_brevis_R2"), Site("Ca_20=m_depressor_caudae_brevis_R2")]),
  MTU("m.depressor_caudae_brevis_L2(2)",
      [Site("Sacrum=m_depressor_caudae_brevis_L3"), Site("Ca_1=m_depressor_caudae_brevis_L3"),
       Site("Ca_2=m_depressor_caudae_brevis_L3"), Site("Ca_4=m_depressor_caudae_brevis_L3"),
       Site("Ca_6=m_depressor_caudae_brevis_L3"), Site("Ca_8=m_depressor_caudae_brevis_L3"),
       Site("Ca_10=m_depressor_caudae_brevis_L3"), Site("Ca_12=m_depressor_caudae_brevis_L3"),
       Site("Ca_14=m_depressor_caudae_brevis_L3"), Site("Ca_16=m_depressor_caudae_brevis_L3"),
       Site("Ca_18=m_depressor_caudae_brevis_L3"), Site("Ca_20=m_depressor_caudae_brevis_L3")]),
  MTU("m.depressor_caudae_brevis_R2(2)",
      [Site("Sacrum=m_depressor_caudae_brevis_R3"), Site("Ca_1=m_depressor_caudae_brevis_R3"),
       Site("Ca_2=m_depressor_caudae_brevis_R3"), Site("Ca_4=m_depressor_caudae_brevis_R3"),
       Site("Ca_6=m_depressor_caudae_brevis_R3"), Site("Ca_8=m_depressor_caudae_brevis_R3"),
       Site("Ca_10=m_depressor_caudae_brevis_R3"), Site("Ca_12=m_depressor_caudae_brevis_R3"),
       Site("Ca_14=m_depressor_caudae_brevis_R3"), Site("Ca_16=m_depressor_caudae_brevis_R3"),
       Site("Ca_18=m_depressor_caudae_brevis_R3"), Site("Ca_20=m_depressor_caudae_brevis_R3")]),
  MTU("m.levator_caudae_brevis_L",
      [Site("L_7=m_levator_caudae_brevis_L"), Site("Sacrum=m_levator_caudae_brevis_L1"),
       Site("Ca_1=m_levator_caudae_brevis_L2"),
       Site("Ca_2=m_levator_caudae_brevis_L2"), Site("Ca_4=m_depressor_caudae_brevis_L2"),
       Site("Ca_6=m_levator_caudae_brevis_L2"), Site("Ca_8=m_depressor_caudae_brevis_L2"),
       Site("Ca_10=m_levator_caudae_brevis_L2"), Site("Ca_12=m_depressor_caudae_brevis_L2"),
       Site("Ca_14=m_levator_caudae_brevis_L2"), Site("Ca_16=m_depressor_caudae_brevis_L2"),
       Site("Ca_18=m_levator_caudae_brevis_L2"), Site("Ca_20=m_depressor_caudae_brevis_L2")]),
  MTU("m.levator_caudae_brevis_R",
      [Site("L_7=m_levator_caudae_brevis_R"), Site("Sacrum=m_levator_caudae_brevis_R1"),
       Site("Ca_1=m_levator_caudae_brevis_R2"),
       Site("Ca_2=m_levator_caudae_brevis_R2"), Site("Ca_4=m_depressor_caudae_brevis_R2"),
       Site("Ca_6=m_levator_caudae_brevis_R2"), Site("Ca_8=m_depressor_caudae_brevis_R2"),
       Site("Ca_10=m_levator_caudae_brevis_R2"), Site("Ca_12=m_depressor_caudae_brevis_R2"),
       Site("Ca_14=m_levator_caudae_brevis_R2"), Site("Ca_16=m_depressor_caudae_brevis_R2"),
       Site("Ca_18=m_levator_caudae_brevis_R2"), Site("Ca_20=m_depressor_caudae_brevis_R2")]),
  MTU("m.levator_caudae_longus_L",
      [Site("L_2=m_levator_caudae_longus_L"), Site("L_4=m_levator_caudae_longus_L"),
       Site("L_6=m_levator_caudae_longus_L"), Site("L_7=m_levator_caudae_longus_L"),
       Site("Sacrum=m_levator_caudae_brevis_L1"), Site("Ca_1=m_levator_caudae_brevis_L2"),
       Site("Ca_2=m_levator_caudae_brevis_L2"), Site("Ca_4=m_depressor_caudae_brevis_L2"),
       Site("Ca_6=m_levator_caudae_brevis_L2"), Site("Ca_8=m_depressor_caudae_brevis_L2"),
       Site("Ca_10=m_levator_caudae_brevis_L2"), Site("Ca_12=m_depressor_caudae_brevis_L2"),
       Site("Ca_14=m_levator_caudae_brevis_L2"), Site("Ca_16=m_depressor_caudae_brevis_L2"),
       Site("Ca_18=m_levator_caudae_brevis_L2"), Site("Ca_20=m_depressor_caudae_brevis_L2")]),
  MTU("m.levator_caudae_longus_R",
      [Site("L_2=m_levator_caudae_longus_R"), Site("L_4=m_levator_caudae_longus_R"),
       Site("L_6=m_levator_caudae_longus_R"), Site("L_7=m_levator_caudae_longus_R"),
       Site("Sacrum=m_levator_caudae_brevis_R1"), Site("Ca_1=m_levator_caudae_brevis_R2"),
       Site("Ca_2=m_levator_caudae_brevis_R2"), Site("Ca_4=m_depressor_caudae_brevis_R2"),
       Site("Ca_6=m_levator_caudae_brevis_R2"), Site("Ca_8=m_depressor_caudae_brevis_R2"),
       Site("Ca_10=m_levator_caudae_brevis_R2"), Site("Ca_12=m_depressor_caudae_brevis_R2"),
       Site("Ca_14=m_levator_caudae_brevis_R2"), Site("Ca_16=m_depressor_caudae_brevis_R2"),
       Site("Ca_18=m_levator_caudae_brevis_R2"), Site("Ca_20=m_depressor_caudae_brevis_R2")]),
  MTU("m.coccygeus_L", [Site("Pelvis=m_coccygeus_L"), Site("Ca_3=m_coccygeus_L")]),
  MTU("m.coccygeus_R", [Site("Pelvis=m_coccygeus_R"), Site("Ca_3=m_coccygeus_R")]),
]

# m.flexor_digitorum_superficialis is missing for right side!
reserve = [

]

# m.flexor_carpi_ulnaris_(L/R): in the current model ulna and carpal accessory belong to the same body, so these muscles
# have no effect; also, including them causes a lengthrange error in mujoco
not_used = [
  MTU("m.flexor_carpi_ulnaris_L", [Site("Ulna_L=m.flexor_carpi_ulnaris_L"),
                                      Site("Carpal_accessory_L=m.flexor_carpi_ulnaris_L")]),
  MTU("m.flexor_carpi_ulnaris_R", [Site("Ulna_R=m.flexor_carpi_ulnaris_R"),
                                      Site("Carpal_accessory_R=m.flexor_carpi_ulnaris_R")]),

]
