import os

asset_folder = '/home/aleksi/Workspace/dm_control/dm_control/suite/dog_assets/extras'


class Tendon:

    def __init__(self, name, sites, scale=None):
        self.name = name
        self.sites = sites
        self.scale = scale


class Site:

    def __init__(self, name, geom=None):
        self.name = name

        # Get geom
        if geom is None:
            self.geom = self.name.split('*')[0]
        else:
            self.geom = geom

        # Get mesh file also
        filename = f'SITE{self.name}.stl'
        if 'extra' in self.name:
            self.mesh_file = os.path.join(asset_folder, 'extra_sites', filename)
        else:
            self.mesh_file = os.path.join(asset_folder, filename)


configs = [Tendon("m.digastricus_L", [Site("Skull*m_digastricus_L"), Site("Mandible*m_digastricus_L")]),
           Tendon("m.digastricus_R", [Site("Skull*m_digastricus_R"), Site("Mandible*m_digastricus_R")]),
           Tendon("m.sternocephalicus_L", [Site("Sternum_1*m_sternocephalicus_L"),
                                           Site("Skull_*m_sternocephalicus_L", "Skull")]),
           Tendon("m.sternocephalicus_R", [Site("Sternum_1*m_sternocephalicus_R"),
                                           Site("Skull_*m_sternocephalicus_R", "Skull")]),
           Tendon("m.brachiocephalicus_L", [Site("humerus_L2*m_brachiocephalicus_", "humerus_L"),
                                            Site("humerus_L1*m_brachiocephalicus_", "humerus_L"),
                                            Site("C_4*m_brachiocephalicus_L_extra_1"),
                                            [[Site("C_2*m_brachiocephalicus_")],
                                             [Site("Skull_1L*m_brachiocephalicus", "Skull")]]]),
           Tendon("m.brachiocephalicus_R", [Site("humerus_R2*m_brachiocephalicus_", "humerus_R"),
                                            Site("humerus_R1*m_brachiocephalicus_", "humerus_R"),
                                            Site("C_4*m_brachiocephalicus_R_extra_1"),
                                            [[Site("C_2*m_brachiocephalicus_")],
                                             [Site("Skull_1R*m_brachiocephalicus", "Skull")]]]),
           Tendon("m.trapezius_L", [Site("Scapula_L*trapezius_extra_1"), Site("Scapula_L*trapezius"),
                                    [[Site("Scapula_L*trapezius_extra_2"),
                                      [[Site("Ligament-1*m_trapezius", "C_3")],
                                       [Site("Ligament-6*m_trapezius", "C_5")]]],
                                     [Site("Scapula_L*trapezius_extra_3"),
                                      [[Site("Ligament-10*m_trapezius", "T_2")],
                                       [Site("Ligament-13*m_trapezius", "T_7")]]]]]),
           Tendon("m.trapezius_R", [Site("Scapula_R*trapezius_extra_1"), Site("Scapula_R*trapezius"),
                                    [[Site("Scapula_R*trapezius_extra_2"),
                                      [[Site("Ligament-1*m_trapezius", "C_3")],
                                       [Site("Ligament-6*m_trapezius", "C_5")]]],
                                     [Site("Scapula_R*trapezius_extra_3"),
                                      [[Site("Ligament-10*m_trapezius", "T_2")],
                                       [Site("Ligament-13*m_trapezius", "T_7")]]]]]),
           Tendon("m.omotransversarius_L", [Site("Scapula_L*m_omotransversarius_L"),
                                            Site("C_1*m_omotransversarius_L")]),
           Tendon("m.omotransversarius_R", [Site("Scapula_R*m_omotransversarius_R"),
                                            Site("C_1*m_omotransversarius_R")]),
           Tendon("m.deltoideus_acromialis_L", [Site("Scapula_L*m_deltoideus_acromialis_L"),
                                                Site("humerus_L*m_deltoideus_acromialis_L")]),
           Tendon("m.deltoideus_scapularis_L", [Site("Scapula_L*m_deltoideus_scapularis_L_extra_1"),
                                                Site("Scapula_L*m_deltoideus_scapularis_L_extra_2"),
                                                Site("humerus_L*m_deltoideus_scapularis_L")]),
           Tendon("m.deltoideus_acromialis_R", [Site("Scapula_R*m_deltoideus_acromialis_R"),
                                                Site("humerus_R*m_deltoideus_acromialis_R")]),
           Tendon("m.deltoideus_scapularis_R", [Site("Scapula_R*m_deltoideus_scapularis_R_extra_1"),
                                                Site("Scapula_R*m_deltoideus_scapularis_R_extra_2"),
                                                Site("humerus_R*m_deltoideus_scapularis_R")]),
           Tendon("m.biceps_brachii_L", [Site("Scapula_L*m_biceps_brachii_L"),
                                         Site("humerus_L*m_biceps_brachii_L_extra_4"),
                                         Site("humerus_L*m_biceps_brachii_L_extra_3"),
                                         Site("Radius_L*m_biceps_brachii_L")], scale=50000),
           Tendon("m.biceps_brachii_R", [Site("Scapula_R*m_biceps_brachii_R"),
                                         Site("humerus_R*m_biceps_brachii_R_extra_4"),
                                         Site("humerus_R*m_biceps_brachii_R_extra_3"),
                                         Site("Radius_R*m_biceps_brachii_R")], scale=50000),
           Tendon("m.pronator_teres_L", [Site("humerus_L*m.pronator_teres_L"), Site("Radius_L*m.pronator_teres_L")]),
           Tendon("m.pronator_teres_R", [Site("humerus_R*m.pronator_teres_R"), Site("Radius_R*m.pronator_teres_R")]),
           Tendon("m.flexor_capri_radialis_L", [Site("humerus_L*m_flexor_capri_radialis_L"),
                                                Site("Carpal_L*m_flexor_capri_radialis_L_extra_1"),
                                                Site("Carpal_II_L*m_flexor_capri_radialis_L_extra_2"),
                                                [[Site("Os_metacarpale_II_L*m_flexor_capri_radialis_L")],
                                                 [Site("Os_metacarpale_III_L*m_flexor_capri_radialis_L")]]]),
           Tendon("m.flexor_capri_radialis_R", [Site("humerus_R*m_flexor_capri_radialis_R"),
                                                Site("Carpal_R*m_flexor_capri_radialis_R_extra_1"),
                                                Site("Carpal_II_R*m_flexor_capri_radialis_R_extra_2"),
                                                [[Site("Os_metacarpale_II_R*m_flexor_capri_radialis_R")],
                                                 [Site("Os_metacarpale_III_R*m_flexor_capri_radialis_R")]]]),
           Tendon("m.flexor_digitorum_superficialis_L",
                  [Site("humerus_L*m_flexor_digitorum_superficialis_L"),
                   Site("Carpal_L*m_flexor_digitorum_superficialis_L_extra_1"),
                   [[Site("Os_metacarpale_II_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_II_L*m_flexor_digitorum_superficialis_L")],
                    [Site("Os_metacarpale_III_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_III_L*m_flexor_digitorum_superficialis_L_extra_1")],
                    [Site("Os_metacarpale_IV_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_IV_L*m_flexor_digitorum_superficialis_L")],
                    [Site("Os_metacarpale_V_L_dot_001*m_flexor_digitorum_superficialis_L_extra_1", "Os_metacarpale_V_L.001"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_V_L*m_flexor_digitorum_superficialis_L")]]]),
           Tendon("m.flexor_digitorum_superficialis_R",
                  [Site("humerus_R*m_flexor_digitorum_superficialis_R"),
                   Site("Carpal_R*m_flexor_digitorum_superficialis_R_extra_1"),
                   [[Site("Os_metacarpale_II_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_II_R*m_flexor_digitorum_superficialis_R")],
                    [Site("Os_metacarpale_III_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_III_R*m_flexor_digitorum_superficialis_R_extra_1")],
                    [Site("Os_metacarpale_IV_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_IV_R*m_flexor_digitorum_superficialis_R")],
                    [Site("Os_metacarpale_V_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_V_R*m_flexor_digitorum_superficialis_R")]]]),
           Tendon("m.flexor_digitorum_profundus_humerus_L",
                  [Site("humerus_L*m_flexor_digitorum_profundus_L"),
                   Site("Ulna_L*m_flexor_digitorum_profundus_L_extra_1"),
                   Site("Carpal_L*m_flexor_digitorum_profundus_L_extra_1"),
                   [[Site("Os_metacarpale_I_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Os_metacarpale_V_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_distalis_digiti_I_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_II_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_II_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_III_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_III_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_IV_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_IV_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_V_L_dot_001*m_flexor_digitorum_profundus_L_extra_1",
                          "Os_metacarpale_V_L.001"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_V_L*m_flexor_digitorum_profundus_L")]]]),
           Tendon("m.flexor_digitorum_profundus_humerus_R",
                  [Site("humerus_R*m_flexor_digitorum_profundus_R"),
                   Site("Ulna_R*m_flexor_digitorum_profundus_R_extra_1"),
                   Site("Carpal_R*m_flexor_digitorum_profundus_R_extra_1"),
                   [[Site("Os_metacarpale_I_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Os_metacarpale_V_R_dot_001*m_flexor_digitorum_profundus_R_extra_1",
                          "Os_metacarpale_V_R.001"),
                     Site("Phalanx_distalis_digiti_I_R*m_flexor_digitorum_profundus_R")],
                    [Site("Os_metacarpale_II_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_II_R*m_flexor_digitorum_profundus_R")],
                    [Site("Os_metacarpale_III_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_III_R*m_flexor_digitorum_profundus_R")],
                    [Site("Os_metacarpale_IV_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_V_R*m_flexor_digitorum_profundus_R.001",
                          "Phalanx_distalis_digiti_IV_R")],
                    [Site("Os_metacarpale_V_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_V_R*m_flexor_digitorum_profundus_R")]]]),
           Tendon("m.triceps_brachii_L", [Site("Ulna_L*m_triceps_brachii_L_extra_1"),
                                          Site("humerus_L*m_triceps_brachii_L_extra_1"),
                                          [[Site("Scapula_L*m_triceps_brachii_long_L")],
                                           [Site("humerus_L*m_triceps_brachii_medial_L")],
                                           [Site("humerus_L*m_triceps_brachii_lateral_L")]]]),
           Tendon("m.triceps_brachii_R", [Site("Ulna_R*m_triceps_brachii_R_extra_1"),
                                          Site("humerus_R*m_triceps_brachii_R_extra_1"),
                                          [[Site("Scapula_R*m_triceps_brachii_long_R")],
                                           [Site("humerus_R*m_triceps_brachii_medial_R")],
                                           [Site("humerus_R*m_triceps_brachii_lateral_R")]]]),
           Tendon("m.anconeus_L", [Site("humerus_L*m_anconeus_L"), Site("Ulna_L*m_anconeus_L")]),
           Tendon("m.anconeus_R", [Site("humerus_R*m_anconeus_R"), Site("Ulna_R*m_anconeus_R")]),
           Tendon("m.coracobrachialis_L", [Site("Scapula_L*m_coracobrachialis_L"),
                                           Site("humerus_L*m_coracobrachialis_L_extra_1"),
                                           Site("humerus_L*m_coracobrachialis_L")]),
           Tendon("m.brachialis_L", [Site("humerus_L*m_brachialis_L"), Site("humerus_L*m_brachialis_L_extra_1"),
                                     Site("humerus_L*m_brachialis_L_extra_2"), Site("Radius_L*m_brachialis_L_extra_1"),
                                     Site("Radius_L*m_brachialis_L")]),
           Tendon("m.coracobrachialis_R", [Site("Scapula_R*m_coracobrachialis_R"),
                                           Site("humerus_R*m_coracobrachialis_R_extra_1"),
                                           Site("humerus_R*m_coracobrachialis_R")]),
           Tendon("m.brachialis_R", [Site("humerus_R*m_brachialis_R"), Site("humerus_R*m_brachialis_R_extra_1"),
                                     Site("humerus_R*m_brachialis_R_extra_2"), Site("Radius_R*m_brachialis_R_extra_1"),
                                     Site("Radius_R*m_brachialis_R")]),
           Tendon("m.extensor_capri_radialis_L", [Site("humerus_L*m_extensor_capri_radialis_L"),
                                                  Site("Carpal_II_L*m_extensor_capri_radialis_L")]),
           Tendon("m.extensor_capri_radialis_R", [Site("humerus_R*m_extensor_capri_radialis_R"),
                                                  Site("Carpal_II_R*m_extensor_capri_radialis_R")]),
           Tendon("m.extensor_capri_ulnaris_L", [Site("humerus_L*m.extensor_capri_ulnaris_L"),
                                                 Site("Os_metacarpale_V_L*m.extensor_capri_ulnaris_L")]),
           Tendon("m.extensor_capri_ulnaris_R", [Site("humerus_R*m.extensor_capri_ulnaris_R"),
                                                 Site("Os_metacarpale_V_R*m.extensor_capri_ulnaris_R")]),
           Tendon("m.extensor_digitorum_lat_R",
                  [Site("Ulna_R*m_extensor_digitorum_lat_R"), Site("Radius_R*m_extensor_digitorum_lat_R_extra_1"),
                   [[Site("Os_metacarpale_V_R*m_extensor_digitorum_lat_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_V_R*m_extensor_digitorum_lat_R_extra_1"),
                     Site("Phalanx_distalis_digiti_V_R*m_extensor_digitorum_lat_R")],
                    [Site("Os_metacarpale_IV_R*m_extensor_digitorum_lat_R_extra_1"),
                     [[Site("Os_metacarpale_IV_R*m_extensor_digitorum_lat_R_extra_2"),
                       Site("Phalanxpmxinutlis_digiti_IV_R*m_extensor_digitorum_lat_R_extra_1"),
                       Site("Phalanx_distalis_digiti_IV_R*m_extensor_digitorum_lat_R")],
                      [Site("Os_metacarpale_III_R*m_extensor_digitorum_lat_R_extra_1"),
                       Site("Phalanxpmxinutlis_digiti_III_R*m_extensor_digitorum_lat_R_extra_1"),
                       Site("Phalanx_distalis_digiti_III_R*m_extensor_digitorum_lat_R")]]]]]),
           Tendon("m.extensor_digitorum_communis_R",
                  [Site("humerus_R*m_extensor_digitorum_communis_R"),
                   Site("Radius_R*m_extensor_digitorum_communis_R_extra_1"),
                   [[Site("Os_metacarpale_V_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_V_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_V_R*m_extensor_digitorum_communis_R")],
                    [Site("Os_metacarpale_IV_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_IV_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_IV_R*m_extensor_digitorum_communis_R")],
                    [Site("Os_metacarpale_III_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_III_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_III_R*m_extensor_digitorum_communis_R")],
                    [Site("Os_metacarpale_II_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_II_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_II_R*m_extensor_digitorum_communis_R")]]]),
           Tendon("m_extensor_digitorum_lat_L",
                  [Site("Ulna_L*m_extensor_digitorum_lat_L"), Site("Radius_L*m_extensor_digitorum_lat_L_extra_1"),
                   [[Site("Os_metacarpale_V_L_dot_001*m_extensor_digitorum_lat_L_extra_1",
                          "Os_metacarpale_V_L.001"),
                     Site("Phalanxpmxinutlis_digiti_V_L*m_extensor_digitorum_lat_L_extra_1"),
                     Site("Phalanx_distalis_digiti_V_L*m_extensor_digitorum_lat_L")],
                    [Site("Os_metacarpale_IV_L*m_extensor_digitorum_lat_L_extra_1"),
                     [[Site("Os_metacarpale_IV_L*m_extensor_digitorum_lat_L_extra_2"),
                       Site("Phalanxpmxinutlis_digiti_IV_L_*m_extensor_digitorum_lat_L_extra_1"),
                       Site("Phalanx_distalis_digiti_IV_L*m_extensor_digitorum_lat_L")],
                      [Site("Os_metacarpale_III_L*m_extensor_digitorum_lat_L_extra_1"),
                       Site("Phalanxpmxinutlis_digiti_III_L_*m_extensor_digitorum_lat_L_extra_1"),
                       Site("Phalanx_distalis_digiti_III_L*m_extensor_digitorum_lat_L")]]]]]),
           Tendon("m.extensor_digitorum_communis_L",
                  [Site("humerus_L*m_extensor_digitorum_communis_L"),
                   Site("Radius_L*m_extensor_digitorum_communis_L_extra_1"),
                   [[Site("Os_metacarpale_V_L_dot_001*m_extensor_digitorum_communis_L_extra_1",
                          "Os_metacarpale_V_L.001"),
                     Site("Phalanxpmxinutlis_digiti_V_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_V_L*m_extensor_digitorum_communis_L")],
                    [Site("Os_metacarpale_IV_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_IV_L_*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_IV_L*m_extensor_digitorum_communis_L")],
                    [Site("Os_metacarpale_III_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_III_L_*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_III_L*m_extensor_digitorum_communis_L")],
                    [Site("Os_metacarpale_II_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_II_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_II_L*m_extensor_digitorum_communis_L")]]]),
           Tendon("m_latissimus_dors_L", [Site("humerus_L*m_latissimus_dors"),
                                          Site("humerus_L*m_latissimus_dors_L_extra_1"),
                                          [[Site("Scapula_L*m_latissimus_dors_L_extra_1"),
                                            Site("T_6*m_latissimus_dors_L_extra_1")],
                                           [Site("Rib_L_7*m_latissimus_dors_L_extra_1"),
                                            Site("Rib_L_12*m_latissimus_dors")]]]),
           Tendon("m_latissimus_dors_R", [Site("humerus_R*m_latissimus_dors"),
                                          Site("humerus_R*m_latissimus_dors_R_extra_1"),
                                          [[Site("Scapula_R*m_latissimus_dors_R_extra_1"),
                                            Site("T_6*m_latissimus_dors_R_extra_1")],
                                           [Site("Rib_R_7*m_latissimus_dors_R_extra_1"),
                                            Site("Rib_R_12*m_latissimus_dors")]]]),
           Tendon("m.pectorales_superficiales_1_L",
                  [Site("humerus_L*m_pectorales_superficiales_1"),
                   Site("humerus_L*m_pectorales_superficiales_1_extra_2"),
                   [[Site("humerus_L*m_pectorales_superficiales_1_extra_1"),
                     Site("Sternum_1*m_pectorales_superficiales_1")],
                    [Site("Sternum_2*m_pectorales_superficiales_1")],
                    [Site("humerus_L*m_pectorales_superficiales_1_extra_3"),
                     Site("Sternum_3*m_pectorales_superficiales_1")]]]),
           Tendon("m.pectorales_superficiales_1_R",
                  [Site("humerus_R*m_pectorales_superficiales_1"),
                   Site("humerus_R*m_pectorales_superficiales_1_extra_2"),
                   [[Site("humerus_R*m_pectorales_superficiales_1_extra_1"),
                     Site("Sternum_1*m_pectorales_superficiales_1")],
                    [Site("Sternum_2*m_pectorales_superficiales_1")],
                    [Site("humerus_R*m_pectorales_superficiales_1_extra_3"),
                     Site("Sternum_3*m_pectorales_superficiales_1")]]]),
           Tendon("m.pectorales_superficiales_2_L",
                  [Site("humerus_L*m_pectorales_superficiales_2"), Site("Sternum_1*m_pectorales_superficiales_2")]),
           Tendon("m.pectorales_superficiales_2_R",
                  [Site("humerus_R*m_pectorales_superficiales_2"), Site("Sternum_1*m_pectorales_superficiales_2")]),
           Tendon("mm.thoracis_m.pectoralis_profundus_L",
                  [Site("humerus_L*mm_thoracis_m_pectoralis_profundus"),
                   Site("Rib_L_1*mm_thoracis_m_pectoralis_profundus"),
                   [[Site("Sternum_1*mm_thoracis_m_pectoralis_profundus")],
                    [Site("Sternum_3*mm_thoracis_m_pectoralis_profundus")],
                    [Site("Rib_L_4*mm_thoracis_m_pectoralis_profundus"),
                     [[Site("Sternum_4*mm_thoracis_m_pectoralis_profundus")],
                      [Site("Sternum_6*mm_thoracis_m_pectoralis_profundus")],
                      [Site("Rib_L_6*mm_thoracis_m_pectoralis_profundus"),
                       Site("Sternum_8*mm_thoracis_m_pectoralis_profundus")]]]]]),
           Tendon("mm.thoracis_m.pectoralis_profundus_R",
                  [Site("humerus_R*mm_thoracis_m_pectoralis_profundus"),
                   Site("Rib_R_1*mm_thoracis_m_pectoralis_profundus"),
                   [[Site("Sternum_1*mm_thoracis_m_pectoralis_profundus")],
                    [Site("Sternum_3*mm_thoracis_m_pectoralis_profundus")],
                    [Site("Rib_R_4*mm_thoracis_m_pectoralis_profundus"),
                     [[Site("Sternum_4*mm_thoracis_m_pectoralis_profundus")],
                      [Site("Sternum_6*mm_thoracis_m_pectoralis_profundus")],
                      [Site("Rib_R_6*mm_thoracis_m_pectoralis_profundus"),
                       Site("Sternum_8*mm_thoracis_m_pectoralis_profundus")]]]]]),
           Tendon("m.obliquus_int_abdominis_L",
                  [Site("Pelvis*m_obliquus_int_abdominis_L"), Site("Pelvis*m_obliquus_int_abdominis_L_extra_1"),
                   [[Site("Rib_L_12*m_obliquus_int_abdominis_L")], [Site("Rib_L_13*m_obliquus_int_abdominis_L")]]]),
           Tendon("m.obliquus_int_abdominis_R",
                  [Site("Pelvis*m_obliquus_int_abdominis_R"), Site("Pelvis*m_obliquus_int_abdominis_R_extra_1"),
                   [[Site("Rib_R_12*m_obliquus_int_abdominis_R")], [Site("Rib_R_13*m_obliquus_int_abdominis_R")]]]),
           Tendon("m.obliquus_ext_abdominis_L",
                  [Site("Pelvis*Mm_abdominis_m.obliquus_ext._abdominis_L"),
                   Site("Pelvis*m_obliquus_int_abdominis_L_extra_1"),
                   [[Site("Rib_L_13*Mm_abdominis_m.obliquus_ext._abdominis_L")],
                    [Site("Rib_L_10*Mm_abdominis_m.obliquus_ext._abdominis_L")],
                    [Site("Rib_L_8*Mm_abdominis_m.obliquus_ext._abdominis_L")],
                    [Site("Rib_L_5*Mm_abdominis_m.obliquus_ext._abdominis_L")]]]),
           Tendon("m.obliquus_ext_abdominis_R",
                  [Site("Pelvis*Mm_abdominis_m.obliquus_ext._abdominis_R"),
                   Site("Pelvis*m_obliquus_int_abdominis_R_extra_1"),
                   [[Site("Rib_R_13*Mm_abdominis_m.obliquus_ext._abdominis_R")],
                    [Site("Rib_R_10*Mm_abdominis_m.obliquus_ext._abdominis_R")],
                    [Site("Rib_R_8*Mm_abdominis_m.obliquus_ext._abdominis_R")],
                    [Site("Rib_R_5*Mm_abdominis_m.obliquus_ext._abdominis_R")]]]),
           Tendon("m.gluteus_medius_L", [Site("Pelvis*m_gluteus_medius_L"), Site("Femoris_L*m_gluteus_medius_L")]),
           Tendon("m.gluteus_medius_R", [Site("Pelvis*m_gluteus_medius_R"), Site("Femoris_R*m_gluteus_medius_R")]),
           Tendon("m.gluteus_profundus_minor_L", [Site("Pelvis*m_gluteus_profundus_minor_L_extra_1"),
                                                  Site("Femoris_L*m_gluteus_profundus_minor_L")], scale=1000),
           Tendon("m.gluteus_profundus_minor_R", [Site("Pelvis*m_gluteus_profundus_minor_R_extra_1"),
                                                  Site("Femoris_R*m_gluteus_profundus_minor_R")], scale=1000),
           Tendon("m.gluteus_superficialis_major_L",
                  [Site("Sacrum*m_gluteus_superficialis_major_L"),
                   Site("Femoris_L*m_gluteus_superficialis_major_L_extra_2"),
                   Site("Femoris_L*m_gluteus_superficialis_major_L_extra_1")], scale=5000),
           Tendon("m.gluteus_superficialis_major_R",
                  [Site("Sacrum*m_gluteus_superficialis_major_R"),
                   Site("Femoris_R*m_gluteus_superficialis_major_R_extra_2"),
                   Site("Femoris_R*m_gluteus_superficialis_major_R_extra_1")], scale=5000),
           Tendon("m.sartorius_L",
                  [Site("Pelvis*m_sartorius_L_extra_1"), Site("Pelvis*m_sartorius_L(2)"),
                   [[Site("Patella_L*m_sartorius_L(2)")],
                    [Site("Femoris_L*m_sartorius_L_extra_1"), Site("Tibia_L*m_sartorius_L")]]], scale=1000),
           Tendon("m.sartorius_R",
                  [Site("Pelvis*m_sartorius_R_extra_1"), Site("Pelvis*m_sartorius_R(2)"),
                   [[Site("Patella_R*m_sartorius_R(2)")],
                    [Site("Femoris_R*m_sartorius_R_extra_1"), Site("Tibia_R*m_sartorius_R")]]], scale=1000),
           Tendon("m_tensor_f.latae_L",
                  [Site("Pelvis*m_tensor_f.latae_L"),
                   Site("Femoris_L*m_tensor_f_latae_L_extra_1")], scale=1000),
           Tendon("m_tensor_f.latae_R",
                  [Site("Pelvis*m_tensor_f.latae_R"),
                   Site("Femoris_R*m_tensor_f_latae_R_extra_1")], scale=1000),
           Tendon("m.tensor_f.antebrachii_L",
                  [Site("Rib_L_3*m_tensor_f_antebrachii_L_extra_1"), Site("Ulna_L*m_tensor_f.antebrachii_L")],
                  scale=1000),
           Tendon("m.tensor_f.antebrachii_R",
                  [Site("Rib_R_3*m_tensor_f_antebrachii_R_extra_1"), Site("Ulna_R*m_tensor_f.antebrachii_R")],
                  scale=1000),
           Tendon("m.semitendinosus_L",
                  [Site("Pelvis*m_semitendinosus_L"), Site("Tibia_L*m_semitendinosus_L_extra_1"),
                   Site("Tibia_L*m_semitendinosus_L")], scale=1000),
           Tendon("m.semitendinosus_R",
                  [Site("Pelvis*m_semitendinosus_R"), Site("Tibia_R*m_semitendinosus_R_extra_1"),
                   Site("Tibia_R*m_semitendinosus_R")], scale=1000),
           Tendon("m.semimembranosus_L", [Site("Pelvis*m_semimembranosus_L_"),
                                          Site("Femoris_fabellae_L_2*m_semimembranosus_L_")], scale=500),
           Tendon("m.semimembranosus_R", [Site("Pelvis*m_semimembranosus_R"),
                                          Site("Femoris_fabellae_R_2*m_semimembranosus_R")], scale=500),
           Tendon("m.biceps_femoris_L",
                  [Site("sacrotuberous_lig_L*m_biceps_femoris_L", "Pelvis"), Site("Pelvis*m_biceps_femoris_L_extra_1"),
                   Site("Femoris_L*m_biceps_femoris_L_extra_1"), Site("Tibia_L*m_biceps_femoris_L_extra_1")],
                  scale=10000),
           Tendon("m.biceps_femoris_R",
                  [Site("sacrotuberous_lig_R*m_biceps_femoris_R", "Pelvis"), Site("Pelvis*m_biceps_femoris_R_extra_1"),
                   Site("Femoris_R*m_biceps_femoris_R_extra_1"), Site("Tibia_R*m_biceps_femoris_R_extra_1")],
                  scale=10000),
           Tendon("m.gracilis_L", [Site("Pelvis*m_gracilis_L"), Site("Tibia_L*m_gracilis_L")], scale=5000),
           Tendon("m.gracilis_R", [Site("Pelvis*m_gracilis_R"), Site("Tibia_R*m_gracilis_R")], scale=5000),
           Tendon("m.gastrocnemius_L", [Site("Calcaneal_tuber_L*m_gastrocnemius_L"),
                                        Site("Tibia_L*m_gastrocnemius_L_extra_1"),
                                        [[Site("Femoris_L1*m_gastrocnemius_L", "Femoris_L")],
                                         [Site("Femoris_L2*m_gastrocnemius_L", "Femoris_L")]]]),
           Tendon("m.gastrocnemius_R", [Site("Calcaneal_tuber_R*m_gastrocnemius_R"),
                                        Site("Tibia_R*m_gastrocnemius_R_extra_1"),
                                        [[Site("Femoris_R1*m_gastrocnemius_R", "Femoris_R")],
                                         [Site("Femoris_R2*m_gastrocnemius_R", "Femoris_R")]]]),
           Tendon("m.tibialis_caudalis_L",
                  [Site("ibula_L*m_tibialis_caudalis_L.001", "Tibia_L"), Site("Tibia_L*m_tibialis_caudalis_L_extra_1"),
                   Site("ibula_L*m_tibialis_caudalis_L", "Tibial_tarsal_L")], scale=1000),
           Tendon("m.tibialis_caudalis_R",
                  [Site("ibula_R*m_tibialis_caudalis_R.001", "Tibia_R"), Site("Tibia_R*m_tibialis_caudalis_R_extra_1"),
                   Site("ibula_R*m_tibialis_caudalis_R", "Tibial_tarsal_R")], scale=1000),
           Tendon("m.tibialis_cranialis_L",
                  [Site("Fibula_L*m_tibialis_cranialis_L"), Site("Tibia_L*m_tibialis_cranialis_L_extra_1"),
                   Site("Tarsus_central_L*m_tibialis_cranialis_L")], scale=10000),
           Tendon("m.tibialis_cranialis_R",
                  [Site("Fibula_R*m_tibialis_cranialis_R"), Site("Tibia_R*m_tibialis_cranialis_R_extra_1"),
                   Site("Tarsus_central_R*m_tibialis_cranialis_R")], scale=10000),
           Tendon("m.adductor_longus_L",
                  [Site("Pelvis*m_adductor_longus_L"), Site("Femoris_L*m_adductor_longus_L")], scale=1000),
           Tendon("m.adductor_longus_R",
                  [Site("Pelvis*m_adductor_longus_R"), Site("Femoris_R*m_adductor_longus_R")], scale=1000),
           Tendon("m.longus_capitis_L",
                  [Site("T-3*m_longus_capitis_L", "T_3"), Site("T-2*m_longus_capitis_L", "T_2"),
                   Site("T-1*m_longus_capitis_L", "T_1"), Site("C_7*m_longus_capitis_L"),
                   Site("C_4*m_longus_capitis_L"),
                   Site("C_3*m_longus_capitis_L"), Site("Skull_*m_longus_capitis_L", "Skull")], scale=1000),
           Tendon("m.longus_capitis_R",
                  [Site("T-3*m_longus_capitis_R", "T_3"), Site("T-2*m_longus_capitis_R", "T_2"),
                   Site("T-1*m_longus_capitis_R", "T_1"), Site("C_7*m_longus_capitis_R"),
                   Site("C_4*m_longus_capitis_R"),
                   Site("C_3*m_longus_capitis_R"), Site("Skull_*m_longus_capitis_R", "Skull")], scale=1000),
           Tendon("m.abductor_pollicis_longus_L",
                  [Site("Radius_L*m_abductor_pollicis_longus_L"), Site("Radius_L*m_abductor_pollicis_longus_L_extra_1"),
                   Site("Carpal_L*m_abductor_pollicis_longus_L_extra_1"),
                   Site("Os_metacarpale_I_L*m_abductor_pollicis_longus_L")]),
           Tendon("m.abductor_pollicis_longus_R",
                  [Site("Radius_R*m_abductor_pollicis_longus_R"), Site("Radius_R*m_abductor_pollicis_longus_R_extra_1"),
                   Site("Carpal_R*m_abductor_pollicis_longus_R_extra_1"),
                   Site("Os_metacarpale_I_R*m_abductor_pollicis_longus_R")]),
           Tendon("m.peroneus_longus_L",
                  [Site("Tibia_L*m_peroneus_longus_L"), Site("Tibia_L*m_peroneus_longus_L_extra_1"),
                   Site("Tarsus_L_IV*m_peroneus_longus_L_extra_1"), Site("Tarsus_L_I*m_peroneus_longus_L")],
                  scale=10000),
           Tendon("m.peroneus_longus_R",
                  [Site("Tibia_R*m_peroneus_longus_R"), Site("Tibia_R*m_peroneus_longus_R_extra_1"),
                   Site("Tarsus_R_IV*m_peroneus_longus_R_extra_1"), Site("Tarsus_R_I*m_peroneus_longus_R")],
                  scale=10000),
           Tendon("m.peroneus_brevis_L",
                  [Site("Fibula_L*m_peroneus_brevis_L"), Site("Fibula_L*m_peroneus_brevis_L_extra_1"),
                   Site("Metatarsi_L_4*m_peroneus_brevis_L")], scale=500),
           Tendon("m.peroneus_brevis_R",
                  [Site("Fibula_R*m_peroneus_brevis_R"), Site("Fibula_R*m_peroneus_brevis_R_extra_1"),
                   Site("Metatarsi_R_4*m_peroneus_brevis_R")], scale=500),
           Tendon("m.extensor_digitorum_longus_L",
                  [Site("Femoris_L*m_extensor_digitorum_longus_L"),
                   Site("Tarsus_central_L*m_extensor_digitorum_longus_L_extra_1"),
                   [[Site("Phalanges_B_L_1*m_extensor_digitorum_longus_L_extra_2"),
                     Site("Phalanges_B_L_1*m_extensor_digitorum_longus_L_extra_1"),
                     Site("Phalanges_B_3_L_1*m_extensor_digitorum_longus_L")],
                    [Site("Phalanges_B_L_2*m_extensor_digitorum_longus_L_extra_2"),
                     Site("Phalanges_B_L_2*m_extensor_digitorum_longus_L_extra_1"),
                     Site("Phalanges_B_3_L_2*m_extensor_digitorum_longus_L")],
                    [Site("Phalanges_B_L_3*m_extensor_digitorum_longus_L_extra_2"),
                     Site("Phalanges_B_L_3*m_extensor_digitorum_longus_L_extra_1"),
                     Site("Phalanges_B_3_L_3*m_extensor_digitorum_longus_L")],
                    [Site("Phalanges_B_L_4*m_extensor_digitorum_longus_L_extra_2"),
                     Site("Phalanges_B_L_4*m_extensor_digitorum_longus_L_extra_1"),
                     Site("Phalanges_B_3_L_4*m_extensor_digitorum_longus_L")]]], scale=50000),
           Tendon("m.extensor_digitorum_longus_R",
                  [Site("Femoris_R*m_extensor_digitorum_longus_R"),
                   Site("Tarsus_central_R*m_extensor_digitorum_longus_R_extra_1"),
                   [[Site("Phalanges_B_R_1*m_extensor_digitorum_longus_R_extra_2"),
                     Site("Phalanges_B_R_1*m_extensor_digitorum_longus_R_extra_1"),
                     Site("Phalanges_B_3_R_1*m_extensor_digitorum_longus_R")],
                    [Site("Phalanges_B_R_2*m_extensor_digitorum_longus_R_extra_2"),
                     Site("Phalanges_B_R_2*m_extensor_digitorum_longus_R_extra_1"),
                     Site("Phalanges_B_3_R_2*m_extensor_digitorum_longus_R")],
                    [Site("Phalanges_B_R_3*m_extensor_digitorum_longus_R_extra_2"),
                     Site("Phalanges_B_R_3*m_extensor_digitorum_longus_R_extra_1"),
                     Site("Phalanges_B_3_R_3*m_extensor_digitorum_longus_R")],
                    [Site("Phalanges_B_R_4*m_extensor_digitorum_longus_R_extra_2"),
                     Site("Phalanges_B_R_4*m_extensor_digitorum_longus_R_extra_1"),
                     Site("Phalanges_B_3_R_4*m_extensor_digitorum_longus_R")]]], scale=50000),
           Tendon("m.flexor_digitorum_profundus_L(2)",
                  [Site("Tibia_L*m_flexor_digitorum_profundus_L(2)_extra_2"),
                   Site("Tibia_L*m_flexor_digitorum_profundus_L(2)_extra_1"),
                   Site("Tarsus_central_L*m_flexor_digitorum_profundus_L(2)_extra_1"),
                   [[Site("Phalanges_B_L_1*m_flexor_digitorum_profundus_L(2)_extra_2"),
                     Site("Phalanges_B_L_1*m_flexor_digitorum_profundus_L(2)_extra_1"),
                     Site("Phalanges_B_3_L_1*m_flexor_digitorum_profundus_L")],
                    [Site("Phalanges_B_L_2*m_flexor_digitorum_profundus_L(2)_extra_2"),
                     Site("Phalanges_B_L_2*m_flexor_digitorum_profundus_L(2)_extra_1"),
                     Site("Phalanges_B_3_L_2*m_flexor_digitorum_profundus_L")],
                    [Site("Phalanges_B_L_3*m_flexor_digitorum_profundus_L(2)_extra_2"),
                     Site("Phalanges_B_L_3*m_flexor_digitorum_profundus_L(2)_extra_1"),
                     Site("Phalanges_B_3_L_3*m_flexor_digitorum_profundus_L")],
                    [Site("Phalanges_B_L_4*m_flexor_digitorum_profundus_L(2)_extra_2"),
                     Site("Phalanges_B_L_4*m_flexor_digitorum_profundus_L(2)_extra_1"),
                     Site("Phalanges_B_3_L_4*m_flexor_digitorum_profundus_L")]]], scale=50000),
           Tendon("m.flexor_digitorum_profundus_R(2)",
                  [Site("Tibia_R*m_flexor_digitorum_profundus_R(2)_extra_2"),
                   Site("Tibia_R*m_flexor_digitorum_profundus_R(2)_extra_1"),
                   Site("Tarsus_central_R*m_flexor_digitorum_profundus_R(2)_extra_1"),
                   [[Site("Phalanges_B_R_1*m_flexor_digitorum_profundus_R(2)_extra_2"),
                     Site("Phalanges_B_R_1*m_flexor_digitorum_profundus_R(2)_extra_1"),
                     Site("Phalanges_B_3_R_1*m_flexor_digitorum_profundus_R")],
                    [Site("Phalanges_B_R_2*m_flexor_digitorum_profundus_R(2)_extra_2"),
                     Site("Phalanges_B_R_2*m_flexor_digitorum_profundus_R(2)_extra_1"),
                     Site("Phalanges_B_3_R_2*m_flexor_digitorum_profundus_R")],
                    [Site("Phalanges_B_R_3*m_flexor_digitorum_profundus_R(2)_extra_2"),
                     Site("Phalanges_B_R_3*m_flexor_digitorum_profundus_R(2)_extra_1"),
                     Site("Phalanges_B_3_R_3*m_flexor_digitorum_profundus_R")],
                    [Site("Phalanges_B_R_4*m_flexor_digitorum_profundus_R(2)_extra_2"),
                     Site("Phalanges_B_R_4*m_flexor_digitorum_profundus_R(2)_extra_1"),
                     Site("Phalanges_B_3_R_4*m_flexor_digitorum_profundus_R")]]], scale=50000),
           Tendon("m.rectus_capitis_ventr_L", [Site("C-1*m_rectus_capitis_ventr_L", "C_1"),
                                               Site("Skull_*m_rectus_capitis_ventr_L", "Skull")], scale=50),
           Tendon("m.rectus_capitis_ventr_R", [Site("C-1*m_rectus_capitis_ventr_R", "C_1"),
                                               Site("Skull_*m_rectus_capitis_ventr_R", "Skull")], scale=50),
           Tendon("m.rectus_capitis_lateralis_L", [Site("C-1*m_rectus_capitis_lateralis_L", "C_1"),
                                                   Site("Skull_*m_rectus_capitis_lateralis_L", "Skull")], scale=50),
           Tendon("m.rectus_capitis_lateralis_R", [Site("C-1*m_rectus_capitis_lateralis_R", "C_1"),
                                                   Site("Skull_*m_rectus_capitis_lateralis_R", "Skull")], scale=50),
           Tendon("m.extensor_digitorum_lateralis_L",
                  [Site("Fibula_L*m_extensor_digitorum_lateralis_L"),
                   Site("Fibula_L*m_extensor_digitorum_lateralis_L_extra_1"),
                   Site("Phalanges_B_L_4*m_extensor_digitorum_lateralis_L")], scale=1000),
           Tendon("m.extensor_digitorum_lateralis_R",
                  [Site("Fibula_R*m_extensor_digitorum_lateralis_R"),
                   Site("Fibula_R*m_extensor_digitorum_lateralis_R_extra_1"),
                   Site("Phalanges_B_R_4*m_extensor_digitorum_lateralis_R")], scale=1000),
           Tendon("m.longissimus_capitis_L",
                  [Site("Pelvis*m_longissimus_capitis_L"), Site("L_4*m_longissimus_capitis_L"),
                   Site("Rib_L_7*m_longissimus_capitis_L"), Site("Rib_L_2*m_longissimus_capitis_L"),
                   Site("T_1*m_longissimus_capitis_L"), Site("C_3*m_longissimus_capitis_L"),
                   Site("Skull_*m_longissimus_capitis_L", "Skull")], scale=10000),
           Tendon("m.longissimus_capitis_R",
                  [Site("Pelvis*m_longissimus_capitis_R"), Site("L_4*m_longissimus_capitis_R"),
                   Site("Rib_R_7*m_longissimus_capitis_R"), Site("Rib_R_2*m_longissimus_capitis_R"),
                   Site("T_1*m_longissimus_capitis_R"), Site("C_3*m_longissimus_capitis_R"),
                   Site("Skull_*m_longissimus_capitis_R", "Skull")], scale=10000),
           Tendon("m.longissimus_cervicis_L",
                  [Site("T-6*m.longissimus_cervicis_L", "T_6"), Site("T_4*m_longissimus_cervicis_L_extra_1"),
                   [[Site("C-3*m.longissimus_cervicis_L", "C_3")], [Site("C-4*m.longissimus_cervicis_L", "C_4")],
                    [Site("C-5*m.longissimus_cervicis_L", "C_5")], [Site("C-6*m.longissimus_cervicis_L", "C_6")]]],
                  scale=10000),
           Tendon("m.longissimus_cervicis_R",
                  [Site("T-6*m.longissimus_cervicis_R", "T_6"), Site("T_4*m_longissimus_cervicis_R_extra_1"),
                   [[Site("C-3*m.longissimus_cervicis_R", "C_3")], [Site("C-4*m.longissimus_cervicis_R", "C_4")],
                    [Site("C-5*m.longissimus_cervicis_R", "C_5")], [Site("C-6*m.longissimus_cervicis_R", "C_6")]]],
                  scale=10000),
           Tendon("m.longissimus_thoracis_L",
                  [Site("L_1*m_longissimus_thoracis_L"), Site("C_7*m_longissimus_thoracis_L")]),
           Tendon("m.longissimus_thoracis_R",
                  [Site("L_1*m_longissimus_thoracis_R"), Site("C_7*m_longissimus_thoracis_R")]),
           Tendon("m.longissimus_lumborum_L",
                  [Site("T_9*m_longissimus_lumborum_L"), Site("L_3*m_longissimus_lumborum_L"),
                   Site("L_6*m_longissimus_lumborum_L"),
                   [[Site("Pelvis*m_longissimus_lumborum_L")], [Site("Sacrum*m_longissimus_lumborum_L")]]], scale=5000),
           Tendon("m.longissimus_lumborum_R",
                  [Site("T_9*m_longissimus_lumborum_R"), Site("L_3*m_longissimus_lumborum_R"),
                   Site("L_6*m_longissimus_lumborum_R"),
                   [[Site("Pelvis*m_longissimus_lumborum_R")], [Site("Sacrum*m_longissimus_lumborum_R")]]], scale=5000),
           Tendon("m.temporalis_L", [Site("Skull_1*m_temporalis_L", "Skull"), Site("Mandible*m_temporalis_L")],
                  scale=50),
           Tendon("m.temporalis_R", [Site("Skull_1*m_temporalis_R", "Skull"), Site("Mandible*m_temporalis_R")],
                  scale=50),
           Tendon("m.masseter_L", [Site("Mandible*m_masseter_L_extra_1"), Site("Skull_2*m_masseter_L", "Skull")],
                  scale=50),
           Tendon("m.masseter_R", [Site("Mandible*m_masseter_R_extra_1"), Site("Skull_2*m_masseter_R", "Skull")],
                  scale=50),
           Tendon("m.pectineus_L", [Site("Pelvis*m_pectineus_L"), Site("Femoris_L*m_pectineus_L")], scale=100),
           Tendon("m.pectineus_R", [Site("Pelvis*m_pectineus_R"), Site("Femoris_R*m_pectineus_R")], scale=100),
           Tendon("m.adductor_magnus_L", [Site("Pelvis*m_adductor_magnus_L"), Site("Femoris_L*m_adductor_magnus_L")],
                  scale=100),
           Tendon("m.adductor_magnus_R", [Site("Pelvis*m_adductor_magnus_R"), Site("Femoris_R*m_adductor_magnus_R")],
                  scale=100),
           Tendon("m.obturatorius_ext_L", [Site("Pelvis*m_obturatorius_ext_L"), Site("Femoris_L*m_obturatorius_ext_L")],
                  scale=5000),
           Tendon("m.obturatorius_int_L",
                  [Site("Pelvis*m_obturatorius_int_L"), Site("Pelvis*m_obturatorius_int_L_extra_1"),
                   Site("Femoris_L*m_obturatorius_int_L")], scale=5000),
           Tendon("m.obturatorius_ext_R", [Site("Pelvis*m_obturatorius_ext_R"), Site("Femoris_R*m_obturatorius_ext_R")],
                  scale=5000),
           Tendon("m.obturatorius_int_R",
                  [Site("Pelvis*m_obturatorius_int_R"), Site("Pelvis*m_obturatorius_int_R_extra_1"),
                   Site("Femoris_R*m_obturatorius_int_R")], scale=5000)
           ]

# m.flexor_digitorum_superficialis is missing for right side!
reserve = [

]


# m.flexor_carpi_ulnaris_(L/R): in the current model ulna and carpal accessory belong to the same body, so these muscles
# have no effect; also, including them causes a lengthrange error in mujoco
not_used = [
    Tendon("m.flexor_carpi_ulnaris_L", [Site("Ulna_L*m.flexor_carpi_ulnaris_L"),
                                        Site("Carpal_accessory_L*m.flexor_carpi_ulnaris_L")], scale=5000),
    Tendon("m.flexor_carpi_ulnaris_R", [Site("Ulna_R*m.flexor_carpi_ulnaris_R"),
                                        Site("Carpal_accessory_R*m.flexor_carpi_ulnaris_R")], scale=5000),

]