import os

asset_folder = '/home/aleksi/Workspace/dm_control/dm_control/suite/dog_assets/extras'


class Tendon:

    def __init__(self, name, sites):
        self.name = name
        self.sites = sites


class Site:

    def __init__(self, name, geom=None):
        self.name = name

        # Get geom
        if geom is None:
            self.geom = self.name.split('*')[0]
        else:
            self.geom = geom

        # Get mesh file also
        filename = f'SITE{self.name}.stl'
        if 'extra' in self.name:
            self.mesh_file = os.path.join(asset_folder, 'extra_sites', filename)
        else:
            self.mesh_file = os.path.join(asset_folder, filename)


configs = [Tendon("m.digastricus_L", [Site("Skull*m_digastricus_L"), Site("Mandible*m_digastricus_L")]),
           Tendon("m.digastricus_R", [Site("Skull*m_digastricus_R"), Site("Mandible*m_digastricus_R")]),
           Tendon("m.sternocephalicus_L", [Site("Sternum_1*m_sternocephalicus_L"),
                                           Site("Skull_*m_sternocephalicus_L", "Skull")]),
           Tendon("m.sternocephalicus_R", [Site("Sternum_1*m_sternocephalicus_R"),
                                           Site("Skull_*m_sternocephalicus_R", "Skull")]),
           Tendon("m.brachiocephalicus_L", [Site("humerus_L2*m_brachiocephalicus_", "humerus_L"),
                                            Site("humerus_L1*m_brachiocephalicus_", "humerus_L"),
                                            Site("C_4*m_brachiocephalicus_L_extra_1"),
                                            [[Site("C_2*m_brachiocephalicus_")],
                                             [Site("Skull_1L*m_brachiocephalicus", "Skull")]]]),
           Tendon("m.brachiocephalicus_R", [Site("humerus_R2*m_brachiocephalicus_", "humerus_R"),
                                            Site("humerus_R1*m_brachiocephalicus_", "humerus_R"),
                                            Site("C_4*m_brachiocephalicus_R_extra_1"),
                                            [[Site("C_2*m_brachiocephalicus_")],
                                             [Site("Skull_1R*m_brachiocephalicus", "Skull")]]]),
           Tendon("m.trapezius_L", [Site("Scapula_L*trapezius_extra_1"), Site("Scapula_L*trapezius"),
                                    [[Site("Scapula_L*trapezius_extra_2"),
                                      [[Site("Ligament-1*m_trapezius", "C_3")],
                                       [Site("Ligament-6*m_trapezius", "C_5")]]],
                                     [Site("Scapula_L*trapezius_extra_3"),
                                      [[Site("Ligament-10*m_trapezius", "T_2")],
                                       [Site("Ligament-13*m_trapezius", "T_7")]]]]]),
           Tendon("m.trapezius_R", [Site("Scapula_R*trapezius_extra_1"), Site("Scapula_R*trapezius"),
                                    [[Site("Scapula_R*trapezius_extra_2"),
                                      [[Site("Ligament-1*m_trapezius", "C_3")],
                                       [Site("Ligament-6*m_trapezius", "C_5")]]],
                                     [Site("Scapula_R*trapezius_extra_3"),
                                      [[Site("Ligament-10*m_trapezius", "T_2")],
                                       [Site("Ligament-13*m_trapezius", "T_7")]]]]]),
           Tendon("m.omotransversarius_L", [Site("Scapula_L*m_omotransversarius_L"),
                                            Site("C_1*m_omotransversarius_L")]),
           Tendon("m.omotransversarius_R", [Site("Scapula_R*m_omotransversarius_R"),
                                            Site("C_1*m_omotransversarius_R")]),
           Tendon("m.deltoideus_acromialis_L", [Site("Scapula_L*m_deltoideus_acromialis_L"),
                                                Site("humerus_L*m_deltoideus_acromialis_L")]),
           Tendon("m.deltoideus_scapularis_L", [Site("Scapula_L*m_deltoideus_scapularis_L_extra_1"),
                                                Site("Scapula_L*m_deltoideus_scapularis_L_extra_2"),
                                                Site("humerus_L*m_deltoideus_scapularis_L")]),
           Tendon("m.deltoideus_acromialis_R", [Site("Scapula_R*m_deltoideus_acromialis_R"),
                                                Site("humerus_R*m_deltoideus_acromialis_R")]),
           Tendon("m.deltoideus_scapularis_R", [Site("Scapula_R*m_deltoideus_scapularis_R_extra_1"),
                                                Site("Scapula_R*m_deltoideus_scapularis_R_extra_2"),
                                                Site("humerus_R*m_deltoideus_scapularis_R")]),
           Tendon("m.biceps_brachii_L", [Site("Scapula_L*m_biceps_brachii_L"),
                                         Site("humerus_L*m_biceps_brachii_L_extra_1"),
                                         [[Site("Ulna_L*m_biceps_brachii_L")], [Site("Radius_L*m_biceps_brachii_L")]]]),
           Tendon("m.biceps_brachii_R", [Site("Scapula_R*m_biceps_brachii_R"),
                                         Site("humerus_R*m_biceps_brachii_R_extra_1"),
                                         [[Site("Ulna_R*m_biceps_brachii_R")], [Site("Radius_R*m_biceps_brachii_R")]]]),
           Tendon("m.pronator_teres_L", [Site("humerus_L*m.pronator_teres_L"), Site("Radius_L*m.pronator_teres_L")]),
           Tendon("m.pronator_teres_R", [Site("humerus_R*m.pronator_teres_R"), Site("Radius_R*m.pronator_teres_R")]),
           Tendon("m.flexor_capri_radialis_L", [Site("humerus_L*m_flexor_capri_radialis_L"),
                                                Site("Carpal_L*m_flexor_capri_radialis_L_extra_1"),
                                                Site("Carpal_II_L*m_flexor_capri_radialis_L_extra_2"),
                                                [[Site("Os_metacarpale_II_L*m_flexor_capri_radialis_L")],
                                                 [Site("Os_metacarpale_III_L*m_flexor_capri_radialis_L")]]]),
           Tendon("m.flexor_capri_radialis_R", [Site("humerus_R*m_flexor_capri_radialis_R"),
                                                Site("Carpal_R*m_flexor_capri_radialis_R_extra_1"),
                                                Site("Carpal_II_R*m_flexor_capri_radialis_R_extra_2"),
                                                [[Site("Os_metacarpale_II_R*m_flexor_capri_radialis_R")],
                                                 [Site("Os_metacarpale_III_R*m_flexor_capri_radialis_R")]]]),
           Tendon("m.flexor_digitorum_superficialis_L",
                  [Site("humerus_L*m_flexor_digitorum_superficialis_L"),
                   Site("Carpal_L*m_flexor_digitorum_superficialis_L_extra_1"),
                   [[Site("Os_metacarpale_II_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_II_L*m_flexor_digitorum_superficialis_L")],
                    [Site("Os_metacarpale_III_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_III_L*m_flexor_digitorum_superficialis_L_extra_1")],
                    [Site("Os_metacarpale_IV_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_IV_L*m_flexor_digitorum_superficialis_L")],
                    [Site("Os_metacarpale_V_L_dot_001*m_flexor_digitorum_superficialis_L_extra_1", "Os_metacarpale_V_L.001"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_superficialis_L_extra_1"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_superficialis_L_extra_2"),
                     Site("Phalanx_distalis_digiti_V_L*m_flexor_digitorum_superficialis_L")]]]),
           Tendon("m.flexor_digitorum_superficialis_R",
                  [Site("humerus_R*m_flexor_digitorum_superficialis_R"),
                   Site("Carpal_R*m_flexor_digitorum_superficialis_R_extra_1"),
                   [[Site("Os_metacarpale_II_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_II_R*m_flexor_digitorum_superficialis_R")],
                    [Site("Os_metacarpale_III_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_III_R*m_flexor_digitorum_superficialis_R_extra_1")],
                    [Site("Os_metacarpale_IV_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_IV_R*m_flexor_digitorum_superficialis_R")],
                    [Site("Os_metacarpale_V_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_superficialis_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_superficialis_R_extra_2"),
                     Site("Phalanx_distalis_digiti_V_R*m_flexor_digitorum_superficialis_R")]]]),
           Tendon("m.flexor_digitorum_profundus_humerus_L",
                  [Site("humerus_L*m_flexor_digitorum_profundus_L"),
                   Site("Ulna_L*m_flexor_digitorum_profundus_L_extra_1"),
                   Site("Carpal_L*m_flexor_digitorum_profundus_L_extra_1"),
                   [[Site("Os_metacarpale_I_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Os_metacarpale_V_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_distalis_digiti_I_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_II_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_II_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_II_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_III_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_III_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_III_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_IV_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_IV_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_IV_L*m_flexor_digitorum_profundus_L")],
                    [Site("Os_metacarpale_V_L_dot_001*m_flexor_digitorum_profundus_L_extra_1",
                          "Os_metacarpale_V_L.001"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_profundus_L_extra_1"),
                     Site("Phalanx_media_digiti_V_L*m_flexor_digitorum_profundus_L_extra_2"),
                     Site("Phalanx_distalis_digiti_V_L*m_flexor_digitorum_profundus_L")]]]),
           Tendon("m.flexor_digitorum_profundus_humerus_R",
                  [Site("humerus_R*m_flexor_digitorum_profundus_R"),
                   Site("Ulna_R*m_flexor_digitorum_profundus_R_extra_1"),
                   Site("Carpal_R*m_flexor_digitorum_profundus_R_extra_1"),
                   [[Site("Os_metacarpale_I_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Os_metacarpale_V_R_dot_001*m_flexor_digitorum_profundus_R_extra_1",
                          "Os_metacarpale_V_R.001"),
                     Site("Phalanx_distalis_digiti_I_R*m_flexor_digitorum_profundus_R")],
                    [Site("Os_metacarpale_II_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_II_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_II_R*m_flexor_digitorum_profundus_R")],
                    [Site("Os_metacarpale_III_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_III_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_III_R*m_flexor_digitorum_profundus_R")],
                    [Site("Os_metacarpale_IV_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_IV_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_V_R*m_flexor_digitorum_profundus_R.001",
                          "Phalanx_distalis_digiti_IV_R")],
                    [Site("Os_metacarpale_V_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_profundus_R_extra_1"),
                     Site("Phalanx_media_digiti_V_R*m_flexor_digitorum_profundus_R_extra_2"),
                     Site("Phalanx_distalis_digiti_V_R*m_flexor_digitorum_profundus_R")]]]),
           Tendon("m.triceps_brachii_L", [Site("Ulna_L*m_triceps_brachii_L_extra_1"),
                                          Site("humerus_L*m_triceps_brachii_L_extra_1"),
                                          [[Site("Scapula_L*m_triceps_brachii_long_L")],
                                           [Site("humerus_L*m_triceps_brachii_medial_L")],
                                           [Site("humerus_L*m_triceps_brachii_lateral_L")]]]),
           Tendon("m.triceps_brachii_R", [Site("Ulna_R*m_triceps_brachii_R_extra_1"),
                                          Site("humerus_R*m_triceps_brachii_R_extra_1"),
                                          [[Site("Scapula_R*m_triceps_brachii_long_R")],
                                           [Site("humerus_R*m_triceps_brachii_medial_R")],
                                           [Site("humerus_R*m_triceps_brachii_lateral_R")]]]),
           Tendon("m.anconeus_L", [Site("humerus_L*m_anconeus_L"), Site("Ulna_L*m_anconeus_L")]),
           Tendon("m.anconeus_R", [Site("humerus_R*m_anconeus_R"), Site("Ulna_R*m_anconeus_R")]),
           Tendon("m.coracobrachialis_L", [Site("Scapula_L*m_coracobrachialis_L"),
                                           Site("humerus_L*m_coracobrachialis_L_extra_1"),
                                           Site("humerus_L*m_coracobrachialis_L")]),
           Tendon("m.brachialis_L", [Site("humerus_L*m_brachialis_L"), Site("humerus_L*m_brachialis_L_extra_1"),
                                     Site("humerus_L*m_brachialis_L_extra_2"), Site("Radius_L*m_brachialis_L_extra_1"),
                                     Site("Radius_L*m_brachialis_L")]),
           Tendon("m.coracobrachialis_R", [Site("Scapula_R*m_coracobrachialis_R"),
                                           Site("humerus_R*m_coracobrachialis_R_extra_1"),
                                           Site("humerus_R*m_coracobrachialis_R")]),
           Tendon("m.brachialis_R", [Site("humerus_R*m_brachialis_R"), Site("humerus_R*m_brachialis_R_extra_1"),
                                     Site("humerus_R*m_brachialis_R_extra_2"), Site("Radius_R*m_brachialis_R_extra_1"),
                                     Site("Radius_R*m_brachialis_R")]),
           Tendon("m.extensor_capri_radialis_L", [Site("humerus_L*m_extensor_capri_radialis_L"),
                                                  Site("Carpal_II_L*m_extensor_capri_radialis_L")]),
           Tendon("m.extensor_capri_radialis_R", [Site("humerus_R*m_extensor_capri_radialis_R"),
                                                  Site("Carpal_II_R*m_extensor_capri_radialis_R")]),
           Tendon("m.extensor_capri_ulnaris_L", [Site("humerus_L*m.extensor_capri_ulnaris_L"),
                                                 Site("Os_metacarpale_V_L*m.extensor_capri_ulnaris_L")]),
           Tendon("m.extensor_capri_ulnaris_R", [Site("humerus_R*m.extensor_capri_ulnaris_R"),
                                                 Site("Os_metacarpale_V_R*m.extensor_capri_ulnaris_R")]),
           Tendon("m.extensor_digitorum_lat_R",
                  [Site("Ulna_R*m_extensor_digitorum_lat_R"), Site("Radius_R*m_extensor_digitorum_lat_R_extra_1"),
                   [[Site("Os_metacarpale_V_R*m_extensor_digitorum_lat_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_V_R*m_extensor_digitorum_lat_R_extra_1"),
                     Site("Phalanx_distalis_digiti_V_R*m_extensor_digitorum_lat_R")],
                    [Site("Os_metacarpale_IV_R*m_extensor_digitorum_lat_R_extra_1"),
                     [[Site("Os_metacarpale_IV_R*m_extensor_digitorum_lat_R_extra_2"),
                       Site("Phalanxpmxinutlis_digiti_IV_R*m_extensor_digitorum_lat_R_extra_1"),
                       Site("Phalanx_distalis_digiti_IV_R*m_extensor_digitorum_lat_R")],
                      [Site("Os_metacarpale_III_R*m_extensor_digitorum_lat_R_extra_1"),
                       Site("Phalanxpmxinutlis_digiti_III_R*m_extensor_digitorum_lat_R_extra_1"),
                       Site("Phalanx_distalis_digiti_III_R*m_extensor_digitorum_lat_R")]]]]]),
           Tendon("m.extensor_digitorum_communis_R",
                  [Site("humerus_R*m_extensor_digitorum_communis_R"),
                   Site("Radius_R*m_extensor_digitorum_communis_R_extra_1"),
                   [[Site("Os_metacarpale_V_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_V_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_V_R*m_extensor_digitorum_communis_R")],
                    [Site("Os_metacarpale_IV_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_IV_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_IV_R*m_extensor_digitorum_communis_R")],
                    [Site("Os_metacarpale_III_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_III_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_III_R*m_extensor_digitorum_communis_R")],
                    [Site("Os_metacarpale_II_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_II_R*m_extensor_digitorum_communis_R_extra_1"),
                     Site("Phalanx_distalis_digiti_II_R*m_extensor_digitorum_communis_R")]]]),
           Tendon("m_extensor_digitorum_lat_L",
                  [Site("Ulna_L*m_extensor_digitorum_lat_L"), Site("Radius_L*m_extensor_digitorum_lat_L_extra_1"),
                   [[Site("Os_metacarpale_V_L_dot_001*m_extensor_digitorum_lat_L_extra_1",
                          "Os_metacarpale_V_L.001"),
                     Site("Phalanxpmxinutlis_digiti_V_L*m_extensor_digitorum_lat_L_extra_1"),
                     Site("Phalanx_distalis_digiti_V_L*m_extensor_digitorum_lat_L")],
                    [Site("Os_metacarpale_IV_L*m_extensor_digitorum_lat_L_extra_1"),
                     [[Site("Os_metacarpale_IV_L*m_extensor_digitorum_lat_L_extra_2"),
                       Site("Phalanxpmxinutlis_digiti_IV_L_*m_extensor_digitorum_lat_L_extra_1"),
                       Site("Phalanx_distalis_digiti_IV_L*m_extensor_digitorum_lat_L")],
                      [Site("Os_metacarpale_III_L*m_extensor_digitorum_lat_L_extra_1"),
                       Site("Phalanxpmxinutlis_digiti_III_L_*m_extensor_digitorum_lat_L_extra_1"),
                       Site("Phalanx_distalis_digiti_III_L*m_extensor_digitorum_lat_L")]]]]]),
           Tendon("m.extensor_digitorum_communis_L",
                  [Site("humerus_L*m_extensor_digitorum_communis_L"),
                   Site("Radius_L*m_extensor_digitorum_communis_L_extra_1"),
                   [[Site("Os_metacarpale_V_L_dot_001*m_extensor_digitorum_communis_L_extra_1",
                          "Os_metacarpale_V_L.001"),
                     Site("Phalanxpmxinutlis_digiti_V_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_V_L*m_extensor_digitorum_communis_L")],
                    [Site("Os_metacarpale_IV_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_IV_L_*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_IV_L*m_extensor_digitorum_communis_L")],
                    [Site("Os_metacarpale_III_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_III_L_*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_III_L*m_extensor_digitorum_communis_L")],
                    [Site("Os_metacarpale_II_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanxpmxinutlis_digiti_II_L*m_extensor_digitorum_communis_L_extra_1"),
                     Site("Phalanx_distalis_digiti_II_L*m_extensor_digitorum_communis_L")]]]),
           Tendon("m_latissimus_dors_L", [Site("humerus_L*m_latissimus_dors"),
                                          Site("humerus_L*m_latissimus_dors_L_extra_1"),
                                          [[Site("Scapula_L*m_latissimus_dors_L_extra_1"),
                                            Site("T_6*m_latissimus_dors_L_extra_1")],
                                           [Site("Rib_L_7*m_latissimus_dors_L_extra_1"),
                                            Site("Rib_L_12*m_latissimus_dors")]]]),
           Tendon("m_latissimus_dors_R", [Site("humerus_R*m_latissimus_dors"),
                                          Site("humerus_R*m_latissimus_dors_R_extra_1"),
                                          [[Site("Scapula_R*m_latissimus_dors_R_extra_1"),
                                            Site("T_6*m_latissimus_dors_R_extra_1")],
                                           [Site("Rib_R_7*m_latissimus_dors_R_extra_1"),
                                            Site("Rib_R_12*m_latissimus_dors")]]])

           ]

# m.flexor_digitorum_superficialis is missing for right side!
reserve = [
]

# m.flexor_carpi_ulnaris_(L/R): in the current model ulna and carpal accessory belong to the same body, so these muscles
# have no effect; also, including them causes a lengthrange error in mujoco
not_used = [
    Tendon("m.flexor_carpi_ulnaris_L", [Site("Ulna_L*m.flexor_carpi_ulnaris_L"),
                                        Site("Carpal_accessory_L*m.flexor_carpi_ulnaris_L")]),
    Tendon("m.flexor_carpi_ulnaris_R", [Site("Ulna_R*m.flexor_carpi_ulnaris_R"),
                                        Site("Carpal_accessory_R*m.flexor_carpi_ulnaris_R")]),

]